package tk.tourwith.project.bbs.review.model;

import java.util.Date;

public class RevList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REV_LIST.REV_NO
     *
     * @mbg.generated Sat Feb 10 13:25:04 KST 2018
     */
    private String rev_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REV_LIST.SJ
     *
     * @mbg.generated Sat Feb 10 13:25:04 KST 2018
     */
    private String sj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REV_LIST.REV_WRITNG_MB_NO
     *
     * @mbg.generated Sat Feb 10 13:25:04 KST 2018
     */
    private String rev_writng_mb_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REV_LIST.DEL_YN
     *
     * @mbg.generated Sat Feb 10 13:25:04 KST 2018
     */
    private String del_yn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REV_LIST.HITCNT
     *
     * @mbg.generated Sat Feb 10 13:25:04 KST 2018
     */
    private Integer hitcnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REV_LIST.CR_NO
     *
     * @mbg.generated Sat Feb 10 13:25:04 KST 2018
     */
    private String cr_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REV_LIST.UPD_DE
     *
     * @mbg.generated Sat Feb 10 13:25:04 KST 2018
     */
    private Date upd_de;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REV_LIST.REG_DE
     *
     * @mbg.generated Sat Feb 10 13:25:04 KST 2018
     */
    private Date REG_de;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REV_LIST.CON
     *
     * @mbg.generated Sat Feb 10 13:25:04 KST 2018
     */
    private String con;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REV_LIST.REV_NO
     *
     * @return the value of REV_LIST.REV_NO
     *
     * @mbg.generated Sat Feb 10 13:25:04 KST 2018
     */
    public String getRev_no() {
        return rev_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REV_LIST.REV_NO
     *
     * @param rev_no the value for REV_LIST.REV_NO
     *
     * @mbg.generated Sat Feb 10 13:25:04 KST 2018
     */
    public void setRev_no(String rev_no) {
        this.rev_no = rev_no == null ? null : rev_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REV_LIST.SJ
     *
     * @return the value of REV_LIST.SJ
     *
     * @mbg.generated Sat Feb 10 13:25:04 KST 2018
     */
    public String getSj() {
        return sj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REV_LIST.SJ
     *
     * @param sj the value for REV_LIST.SJ
     *
     * @mbg.generated Sat Feb 10 13:25:04 KST 2018
     */
    public void setSj(String sj) {
        this.sj = sj == null ? null : sj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REV_LIST.REV_WRITNG_MB_NO
     *
     * @return the value of REV_LIST.REV_WRITNG_MB_NO
     *
     * @mbg.generated Sat Feb 10 13:25:04 KST 2018
     */
    public String getRev_writng_mb_no() {
        return rev_writng_mb_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REV_LIST.REV_WRITNG_MB_NO
     *
     * @param rev_writng_mb_no the value for REV_LIST.REV_WRITNG_MB_NO
     *
     * @mbg.generated Sat Feb 10 13:25:04 KST 2018
     */
    public void setRev_writng_mb_no(String rev_writng_mb_no) {
        this.rev_writng_mb_no = rev_writng_mb_no == null ? null : rev_writng_mb_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REV_LIST.DEL_YN
     *
     * @return the value of REV_LIST.DEL_YN
     *
     * @mbg.generated Sat Feb 10 13:25:04 KST 2018
     */
    public String getDel_yn() {
        return del_yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REV_LIST.DEL_YN
     *
     * @param del_yn the value for REV_LIST.DEL_YN
     *
     * @mbg.generated Sat Feb 10 13:25:04 KST 2018
     */
    public void setDel_yn(String del_yn) {
        this.del_yn = del_yn == null ? null : del_yn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REV_LIST.HITCNT
     *
     * @return the value of REV_LIST.HITCNT
     *
     * @mbg.generated Sat Feb 10 13:25:04 KST 2018
     */
    public Integer getHitcnt() {
        return hitcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REV_LIST.HITCNT
     *
     * @param hitcnt the value for REV_LIST.HITCNT
     *
     * @mbg.generated Sat Feb 10 13:25:04 KST 2018
     */
    public void setHitcnt(Integer hitcnt) {
        this.hitcnt = hitcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REV_LIST.CR_NO
     *
     * @return the value of REV_LIST.CR_NO
     *
     * @mbg.generated Sat Feb 10 13:25:04 KST 2018
     */
    public String getCr_no() {
        return cr_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REV_LIST.CR_NO
     *
     * @param cr_no the value for REV_LIST.CR_NO
     *
     * @mbg.generated Sat Feb 10 13:25:04 KST 2018
     */
    public void setCr_no(String cr_no) {
        this.cr_no = cr_no == null ? null : cr_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REV_LIST.UPD_DE
     *
     * @return the value of REV_LIST.UPD_DE
     *
     * @mbg.generated Sat Feb 10 13:25:04 KST 2018
     */
    public Date getUpd_de() {
        return upd_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REV_LIST.UPD_DE
     *
     * @param upd_de the value for REV_LIST.UPD_DE
     *
     * @mbg.generated Sat Feb 10 13:25:04 KST 2018
     */
    public void setUpd_de(Date upd_de) {
        this.upd_de = upd_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REV_LIST.REG_DE
     *
     * @return the value of REV_LIST.REG_DE
     *
     * @mbg.generated Sat Feb 10 13:25:04 KST 2018
     */
    public Date getREG_de() {
        return REG_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REV_LIST.REG_DE
     *
     * @param REG_de the value for REV_LIST.REG_DE
     *
     * @mbg.generated Sat Feb 10 13:25:04 KST 2018
     */
    public void setREG_de(Date REG_de) {
        this.REG_de = REG_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REV_LIST.CON
     *
     * @return the value of REV_LIST.CON
     *
     * @mbg.generated Sat Feb 10 13:25:04 KST 2018
     */
    public String getCon() {
        return con;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REV_LIST.CON
     *
     * @param con the value for REV_LIST.CON
     *
     * @mbg.generated Sat Feb 10 13:25:04 KST 2018
     */
    public void setCon(String con) {
        this.con = con == null ? null : con.trim();
    }
}