package tk.tourwith.project.crew.room.event.model;

import java.util.Date;

public class CrEventList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_EVENT_LIST.EVENT_NO
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    private String event_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_EVENT_LIST.EVENT_NM
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    private String event_nm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_EVENT_LIST.EVENT_CON
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    private String event_con;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_EVENT_LIST.BGNDT
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    private Date bgndt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_EVENT_LIST.ENDDT
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    private Date enddt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_EVENT_LIST.CR_NO
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    private String cr_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_EVENT_LIST.REG_DE
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    private Date reg_de;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_EVENT_LIST.UPD_DE
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    private Date upd_de;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_EVENT_LIST.DEL_YN
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    private String del_yn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_EVENT_LIST.WRTER
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    private String wrter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_EVENT_LIST.UPDUSR
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    private String updusr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_EVENT_LIST.UPD_POSBL_YN
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    private String upd_posbl_yn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_EVENT_LIST.EVENT_NO
     *
     * @return the value of CR_EVENT_LIST.EVENT_NO
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    public String getEvent_no() {
        return event_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_EVENT_LIST.EVENT_NO
     *
     * @param event_no the value for CR_EVENT_LIST.EVENT_NO
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    public void setEvent_no(String event_no) {
        this.event_no = event_no == null ? null : event_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_EVENT_LIST.EVENT_NM
     *
     * @return the value of CR_EVENT_LIST.EVENT_NM
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    public String getEvent_nm() {
        return event_nm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_EVENT_LIST.EVENT_NM
     *
     * @param event_nm the value for CR_EVENT_LIST.EVENT_NM
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    public void setEvent_nm(String event_nm) {
        this.event_nm = event_nm == null ? null : event_nm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_EVENT_LIST.EVENT_CON
     *
     * @return the value of CR_EVENT_LIST.EVENT_CON
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    public String getEvent_con() {
        return event_con;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_EVENT_LIST.EVENT_CON
     *
     * @param event_con the value for CR_EVENT_LIST.EVENT_CON
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    public void setEvent_con(String event_con) {
        this.event_con = event_con == null ? null : event_con.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_EVENT_LIST.BGNDT
     *
     * @return the value of CR_EVENT_LIST.BGNDT
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    public Date getBgndt() {
        return bgndt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_EVENT_LIST.BGNDT
     *
     * @param bgndt the value for CR_EVENT_LIST.BGNDT
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    public void setBgndt(Date bgndt) {
        this.bgndt = bgndt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_EVENT_LIST.ENDDT
     *
     * @return the value of CR_EVENT_LIST.ENDDT
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    public Date getEnddt() {
        return enddt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_EVENT_LIST.ENDDT
     *
     * @param enddt the value for CR_EVENT_LIST.ENDDT
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    public void setEnddt(Date enddt) {
        this.enddt = enddt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_EVENT_LIST.CR_NO
     *
     * @return the value of CR_EVENT_LIST.CR_NO
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    public String getCr_no() {
        return cr_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_EVENT_LIST.CR_NO
     *
     * @param cr_no the value for CR_EVENT_LIST.CR_NO
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    public void setCr_no(String cr_no) {
        this.cr_no = cr_no == null ? null : cr_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_EVENT_LIST.REG_DE
     *
     * @return the value of CR_EVENT_LIST.REG_DE
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    public Date getReg_de() {
        return reg_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_EVENT_LIST.REG_DE
     *
     * @param reg_de the value for CR_EVENT_LIST.REG_DE
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    public void setReg_de(Date reg_de) {
        this.reg_de = reg_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_EVENT_LIST.UPD_DE
     *
     * @return the value of CR_EVENT_LIST.UPD_DE
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    public Date getUpd_de() {
        return upd_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_EVENT_LIST.UPD_DE
     *
     * @param upd_de the value for CR_EVENT_LIST.UPD_DE
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    public void setUpd_de(Date upd_de) {
        this.upd_de = upd_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_EVENT_LIST.DEL_YN
     *
     * @return the value of CR_EVENT_LIST.DEL_YN
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    public String getDel_yn() {
        return del_yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_EVENT_LIST.DEL_YN
     *
     * @param del_yn the value for CR_EVENT_LIST.DEL_YN
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    public void setDel_yn(String del_yn) {
        this.del_yn = del_yn == null ? null : del_yn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_EVENT_LIST.WRTER
     *
     * @return the value of CR_EVENT_LIST.WRTER
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    public String getWrter() {
        return wrter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_EVENT_LIST.WRTER
     *
     * @param wrter the value for CR_EVENT_LIST.WRTER
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    public void setWrter(String wrter) {
        this.wrter = wrter == null ? null : wrter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_EVENT_LIST.UPDUSR
     *
     * @return the value of CR_EVENT_LIST.UPDUSR
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    public String getUpdusr() {
        return updusr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_EVENT_LIST.UPDUSR
     *
     * @param updusr the value for CR_EVENT_LIST.UPDUSR
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    public void setUpdusr(String updusr) {
        this.updusr = updusr == null ? null : updusr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_EVENT_LIST.UPD_POSBL_YN
     *
     * @return the value of CR_EVENT_LIST.UPD_POSBL_YN
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    public String getUpd_posbl_yn() {
        return upd_posbl_yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_EVENT_LIST.UPD_POSBL_YN
     *
     * @param upd_posbl_yn the value for CR_EVENT_LIST.UPD_POSBL_YN
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    public void setUpd_posbl_yn(String upd_posbl_yn) {
        this.upd_posbl_yn = upd_posbl_yn == null ? null : upd_posbl_yn.trim();
    }
}