package tk.tourwith.project.reply.review.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tk.tourwith.project.reply.review.model.RevRplyList;
import tk.tourwith.project.reply.review.model.RevRplyListExample;

public interface RevRplyListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REV_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    long countByExample(RevRplyListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REV_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    int deleteByExample(RevRplyListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REV_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    int insert(RevRplyList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REV_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    int insertSelective(RevRplyList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REV_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    List<RevRplyList> selectByExampleWithBLOBs(RevRplyListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REV_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    List<RevRplyList> selectByExample(RevRplyListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REV_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    int updateByExampleSelective(@Param("record") RevRplyList record, @Param("example") RevRplyListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REV_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") RevRplyList record, @Param("example") RevRplyListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REV_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    int updateByExample(@Param("record") RevRplyList record, @Param("example") RevRplyListExample example);
}