package tk.tourwith.project.crew.room.gis.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tk.tourwith.project.crew.room.gis.model.CrGisCrdntList;
import tk.tourwith.project.crew.room.gis.model.CrGisCrdntListExample;

public interface CrGisCrdntListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_GIS_CRDNT_LIST
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    long countByExample(CrGisCrdntListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_GIS_CRDNT_LIST
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    int deleteByExample(CrGisCrdntListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_GIS_CRDNT_LIST
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    int insert(CrGisCrdntList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_GIS_CRDNT_LIST
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    int insertSelective(CrGisCrdntList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_GIS_CRDNT_LIST
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    List<CrGisCrdntList> selectByExample(CrGisCrdntListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_GIS_CRDNT_LIST
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    int updateByExampleSelective(@Param("record") CrGisCrdntList record, @Param("example") CrGisCrdntListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_GIS_CRDNT_LIST
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    int updateByExample(@Param("record") CrGisCrdntList record, @Param("example") CrGisCrdntListExample example);
}