package tk.tourwith.project.reply.crew.model;

import java.util.Date;

public class CrRplyList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_RPLY_LIST.CR_RPLY_NO
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    private String sj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_RPLY_LIST.CR_NO
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    private String con;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_RPLY_LIST.REG_DE
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    private Date hitcnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_RPLY_LIST.DEL_YN
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    private String upd_de;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_RPLY_LIST.WRITNG_MB_NO
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    private String del_yn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_RPLY_LIST.UPD_DE
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    private Date cr_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_RPLY_LIST.PARNTS_RPLY_NO
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    private String wrter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_RPLY_LIST.CON
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    private String reg_de;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_RPLY_LIST.CR_RPLY_NO
     *
     * @return the value of CR_RPLY_LIST.CR_RPLY_NO
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    public String getSj() {
        return sj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_RPLY_LIST.CR_RPLY_NO
     *
     * @param sj the value for CR_RPLY_LIST.CR_RPLY_NO
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    public void setSj(String sj) {
        this.sj = sj == null ? null : sj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_RPLY_LIST.CR_NO
     *
     * @return the value of CR_RPLY_LIST.CR_NO
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    public String getCon() {
        return con;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_RPLY_LIST.CR_NO
     *
     * @param con the value for CR_RPLY_LIST.CR_NO
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    public void setCon(String con) {
        this.con = con == null ? null : con.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_RPLY_LIST.REG_DE
     *
     * @return the value of CR_RPLY_LIST.REG_DE
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    public Date getHitcnt() {
        return hitcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_RPLY_LIST.REG_DE
     *
     * @param hitcnt the value for CR_RPLY_LIST.REG_DE
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    public void setHitcnt(Date hitcnt) {
        this.hitcnt = hitcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_RPLY_LIST.DEL_YN
     *
     * @return the value of CR_RPLY_LIST.DEL_YN
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    public String getUpd_de() {
        return upd_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_RPLY_LIST.DEL_YN
     *
     * @param upd_de the value for CR_RPLY_LIST.DEL_YN
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    public void setUpd_de(String upd_de) {
        this.upd_de = upd_de == null ? null : upd_de.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_RPLY_LIST.WRITNG_MB_NO
     *
     * @return the value of CR_RPLY_LIST.WRITNG_MB_NO
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    public String getDel_yn() {
        return del_yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_RPLY_LIST.WRITNG_MB_NO
     *
     * @param del_yn the value for CR_RPLY_LIST.WRITNG_MB_NO
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    public void setDel_yn(String del_yn) {
        this.del_yn = del_yn == null ? null : del_yn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_RPLY_LIST.UPD_DE
     *
     * @return the value of CR_RPLY_LIST.UPD_DE
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    public Date getCr_no() {
        return cr_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_RPLY_LIST.UPD_DE
     *
     * @param cr_no the value for CR_RPLY_LIST.UPD_DE
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    public void setCr_no(Date cr_no) {
        this.cr_no = cr_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_RPLY_LIST.PARNTS_RPLY_NO
     *
     * @return the value of CR_RPLY_LIST.PARNTS_RPLY_NO
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    public String getWrter() {
        return wrter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_RPLY_LIST.PARNTS_RPLY_NO
     *
     * @param wrter the value for CR_RPLY_LIST.PARNTS_RPLY_NO
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    public void setWrter(String wrter) {
        this.wrter = wrter == null ? null : wrter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_RPLY_LIST.CON
     *
     * @return the value of CR_RPLY_LIST.CON
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    public String getReg_de() {
        return reg_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_RPLY_LIST.CON
     *
     * @param reg_de the value for CR_RPLY_LIST.CON
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    public void setReg_de(String reg_de) {
        this.reg_de = reg_de == null ? null : reg_de.trim();
    }
}