package tk.tourwith.project.bbs.faq.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tk.tourwith.project.bbs.faq.model.FaqList;
import tk.tourwith.project.bbs.faq.model.FaqListExample;

public interface FaqListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FAQ_LIST
     *
     * @mbg.generated Sat Feb 10 13:14:35 KST 2018
     */
    long countByExample(FaqListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FAQ_LIST
     *
     * @mbg.generated Sat Feb 10 13:14:35 KST 2018
     */
    int deleteByExample(FaqListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FAQ_LIST
     *
     * @mbg.generated Sat Feb 10 13:14:35 KST 2018
     */
    int insert(FaqList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FAQ_LIST
     *
     * @mbg.generated Sat Feb 10 13:14:35 KST 2018
     */
    int insertSelective(FaqList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FAQ_LIST
     *
     * @mbg.generated Sat Feb 10 13:14:35 KST 2018
     */
    List<FaqList> selectByExampleWithBLOBs(FaqListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FAQ_LIST
     *
     * @mbg.generated Sat Feb 10 13:14:35 KST 2018
     */
    List<FaqList> selectByExample(FaqListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FAQ_LIST
     *
     * @mbg.generated Sat Feb 10 13:14:35 KST 2018
     */
    int updateByExampleSelective(@Param("record") FaqList record, @Param("example") FaqListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FAQ_LIST
     *
     * @mbg.generated Sat Feb 10 13:14:35 KST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") FaqList record, @Param("example") FaqListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FAQ_LIST
     *
     * @mbg.generated Sat Feb 10 13:14:35 KST 2018
     */
    int updateByExample(@Param("record") FaqList record, @Param("example") FaqListExample example);
}