package tk.tourwith.project.reply.review.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RevRplyListExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table REV_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table REV_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table REV_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REV_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    public RevRplyListExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REV_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REV_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REV_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REV_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REV_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REV_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REV_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REV_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REV_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table REV_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table REV_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRev_rply_noIsNull() {
            addCriterion("REV_RPLY_NO is null");
            return (Criteria) this;
        }

        public Criteria andRev_rply_noIsNotNull() {
            addCriterion("REV_RPLY_NO is not null");
            return (Criteria) this;
        }

        public Criteria andRev_rply_noEqualTo(String value) {
            addCriterion("REV_RPLY_NO =", value, "rev_rply_no");
            return (Criteria) this;
        }

        public Criteria andRev_rply_noNotEqualTo(String value) {
            addCriterion("REV_RPLY_NO <>", value, "rev_rply_no");
            return (Criteria) this;
        }

        public Criteria andRev_rply_noGreaterThan(String value) {
            addCriterion("REV_RPLY_NO >", value, "rev_rply_no");
            return (Criteria) this;
        }

        public Criteria andRev_rply_noGreaterThanOrEqualTo(String value) {
            addCriterion("REV_RPLY_NO >=", value, "rev_rply_no");
            return (Criteria) this;
        }

        public Criteria andRev_rply_noLessThan(String value) {
            addCriterion("REV_RPLY_NO <", value, "rev_rply_no");
            return (Criteria) this;
        }

        public Criteria andRev_rply_noLessThanOrEqualTo(String value) {
            addCriterion("REV_RPLY_NO <=", value, "rev_rply_no");
            return (Criteria) this;
        }

        public Criteria andRev_rply_noLike(String value) {
            addCriterion("REV_RPLY_NO like", value, "rev_rply_no");
            return (Criteria) this;
        }

        public Criteria andRev_rply_noNotLike(String value) {
            addCriterion("REV_RPLY_NO not like", value, "rev_rply_no");
            return (Criteria) this;
        }

        public Criteria andRev_rply_noIn(List<String> values) {
            addCriterion("REV_RPLY_NO in", values, "rev_rply_no");
            return (Criteria) this;
        }

        public Criteria andRev_rply_noNotIn(List<String> values) {
            addCriterion("REV_RPLY_NO not in", values, "rev_rply_no");
            return (Criteria) this;
        }

        public Criteria andRev_rply_noBetween(String value1, String value2) {
            addCriterion("REV_RPLY_NO between", value1, value2, "rev_rply_no");
            return (Criteria) this;
        }

        public Criteria andRev_rply_noNotBetween(String value1, String value2) {
            addCriterion("REV_RPLY_NO not between", value1, value2, "rev_rply_no");
            return (Criteria) this;
        }

        public Criteria andRev_noIsNull() {
            addCriterion("REV_NO is null");
            return (Criteria) this;
        }

        public Criteria andRev_noIsNotNull() {
            addCriterion("REV_NO is not null");
            return (Criteria) this;
        }

        public Criteria andRev_noEqualTo(String value) {
            addCriterion("REV_NO =", value, "rev_no");
            return (Criteria) this;
        }

        public Criteria andRev_noNotEqualTo(String value) {
            addCriterion("REV_NO <>", value, "rev_no");
            return (Criteria) this;
        }

        public Criteria andRev_noGreaterThan(String value) {
            addCriterion("REV_NO >", value, "rev_no");
            return (Criteria) this;
        }

        public Criteria andRev_noGreaterThanOrEqualTo(String value) {
            addCriterion("REV_NO >=", value, "rev_no");
            return (Criteria) this;
        }

        public Criteria andRev_noLessThan(String value) {
            addCriterion("REV_NO <", value, "rev_no");
            return (Criteria) this;
        }

        public Criteria andRev_noLessThanOrEqualTo(String value) {
            addCriterion("REV_NO <=", value, "rev_no");
            return (Criteria) this;
        }

        public Criteria andRev_noLike(String value) {
            addCriterion("REV_NO like", value, "rev_no");
            return (Criteria) this;
        }

        public Criteria andRev_noNotLike(String value) {
            addCriterion("REV_NO not like", value, "rev_no");
            return (Criteria) this;
        }

        public Criteria andRev_noIn(List<String> values) {
            addCriterion("REV_NO in", values, "rev_no");
            return (Criteria) this;
        }

        public Criteria andRev_noNotIn(List<String> values) {
            addCriterion("REV_NO not in", values, "rev_no");
            return (Criteria) this;
        }

        public Criteria andRev_noBetween(String value1, String value2) {
            addCriterion("REV_NO between", value1, value2, "rev_no");
            return (Criteria) this;
        }

        public Criteria andRev_noNotBetween(String value1, String value2) {
            addCriterion("REV_NO not between", value1, value2, "rev_no");
            return (Criteria) this;
        }

        public Criteria andParnts_rply_noIsNull() {
            addCriterion("PARNTS_RPLY_NO is null");
            return (Criteria) this;
        }

        public Criteria andParnts_rply_noIsNotNull() {
            addCriterion("PARNTS_RPLY_NO is not null");
            return (Criteria) this;
        }

        public Criteria andParnts_rply_noEqualTo(String value) {
            addCriterion("PARNTS_RPLY_NO =", value, "parnts_rply_no");
            return (Criteria) this;
        }

        public Criteria andParnts_rply_noNotEqualTo(String value) {
            addCriterion("PARNTS_RPLY_NO <>", value, "parnts_rply_no");
            return (Criteria) this;
        }

        public Criteria andParnts_rply_noGreaterThan(String value) {
            addCriterion("PARNTS_RPLY_NO >", value, "parnts_rply_no");
            return (Criteria) this;
        }

        public Criteria andParnts_rply_noGreaterThanOrEqualTo(String value) {
            addCriterion("PARNTS_RPLY_NO >=", value, "parnts_rply_no");
            return (Criteria) this;
        }

        public Criteria andParnts_rply_noLessThan(String value) {
            addCriterion("PARNTS_RPLY_NO <", value, "parnts_rply_no");
            return (Criteria) this;
        }

        public Criteria andParnts_rply_noLessThanOrEqualTo(String value) {
            addCriterion("PARNTS_RPLY_NO <=", value, "parnts_rply_no");
            return (Criteria) this;
        }

        public Criteria andParnts_rply_noLike(String value) {
            addCriterion("PARNTS_RPLY_NO like", value, "parnts_rply_no");
            return (Criteria) this;
        }

        public Criteria andParnts_rply_noNotLike(String value) {
            addCriterion("PARNTS_RPLY_NO not like", value, "parnts_rply_no");
            return (Criteria) this;
        }

        public Criteria andParnts_rply_noIn(List<String> values) {
            addCriterion("PARNTS_RPLY_NO in", values, "parnts_rply_no");
            return (Criteria) this;
        }

        public Criteria andParnts_rply_noNotIn(List<String> values) {
            addCriterion("PARNTS_RPLY_NO not in", values, "parnts_rply_no");
            return (Criteria) this;
        }

        public Criteria andParnts_rply_noBetween(String value1, String value2) {
            addCriterion("PARNTS_RPLY_NO between", value1, value2, "parnts_rply_no");
            return (Criteria) this;
        }

        public Criteria andParnts_rply_noNotBetween(String value1, String value2) {
            addCriterion("PARNTS_RPLY_NO not between", value1, value2, "parnts_rply_no");
            return (Criteria) this;
        }

        public Criteria andWritng_mb_noIsNull() {
            addCriterion("WRITNG_MB_NO is null");
            return (Criteria) this;
        }

        public Criteria andWritng_mb_noIsNotNull() {
            addCriterion("WRITNG_MB_NO is not null");
            return (Criteria) this;
        }

        public Criteria andWritng_mb_noEqualTo(String value) {
            addCriterion("WRITNG_MB_NO =", value, "writng_mb_no");
            return (Criteria) this;
        }

        public Criteria andWritng_mb_noNotEqualTo(String value) {
            addCriterion("WRITNG_MB_NO <>", value, "writng_mb_no");
            return (Criteria) this;
        }

        public Criteria andWritng_mb_noGreaterThan(String value) {
            addCriterion("WRITNG_MB_NO >", value, "writng_mb_no");
            return (Criteria) this;
        }

        public Criteria andWritng_mb_noGreaterThanOrEqualTo(String value) {
            addCriterion("WRITNG_MB_NO >=", value, "writng_mb_no");
            return (Criteria) this;
        }

        public Criteria andWritng_mb_noLessThan(String value) {
            addCriterion("WRITNG_MB_NO <", value, "writng_mb_no");
            return (Criteria) this;
        }

        public Criteria andWritng_mb_noLessThanOrEqualTo(String value) {
            addCriterion("WRITNG_MB_NO <=", value, "writng_mb_no");
            return (Criteria) this;
        }

        public Criteria andWritng_mb_noLike(String value) {
            addCriterion("WRITNG_MB_NO like", value, "writng_mb_no");
            return (Criteria) this;
        }

        public Criteria andWritng_mb_noNotLike(String value) {
            addCriterion("WRITNG_MB_NO not like", value, "writng_mb_no");
            return (Criteria) this;
        }

        public Criteria andWritng_mb_noIn(List<String> values) {
            addCriterion("WRITNG_MB_NO in", values, "writng_mb_no");
            return (Criteria) this;
        }

        public Criteria andWritng_mb_noNotIn(List<String> values) {
            addCriterion("WRITNG_MB_NO not in", values, "writng_mb_no");
            return (Criteria) this;
        }

        public Criteria andWritng_mb_noBetween(String value1, String value2) {
            addCriterion("WRITNG_MB_NO between", value1, value2, "writng_mb_no");
            return (Criteria) this;
        }

        public Criteria andWritng_mb_noNotBetween(String value1, String value2) {
            addCriterion("WRITNG_MB_NO not between", value1, value2, "writng_mb_no");
            return (Criteria) this;
        }

        public Criteria andReg_deIsNull() {
            addCriterion("REG_DE is null");
            return (Criteria) this;
        }

        public Criteria andReg_deIsNotNull() {
            addCriterion("REG_DE is not null");
            return (Criteria) this;
        }

        public Criteria andReg_deEqualTo(Date value) {
            addCriterion("REG_DE =", value, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deNotEqualTo(Date value) {
            addCriterion("REG_DE <>", value, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deGreaterThan(Date value) {
            addCriterion("REG_DE >", value, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deGreaterThanOrEqualTo(Date value) {
            addCriterion("REG_DE >=", value, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deLessThan(Date value) {
            addCriterion("REG_DE <", value, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deLessThanOrEqualTo(Date value) {
            addCriterion("REG_DE <=", value, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deIn(List<Date> values) {
            addCriterion("REG_DE in", values, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deNotIn(List<Date> values) {
            addCriterion("REG_DE not in", values, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deBetween(Date value1, Date value2) {
            addCriterion("REG_DE between", value1, value2, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deNotBetween(Date value1, Date value2) {
            addCriterion("REG_DE not between", value1, value2, "reg_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deIsNull() {
            addCriterion("UPD_DE is null");
            return (Criteria) this;
        }

        public Criteria andUpd_deIsNotNull() {
            addCriterion("UPD_DE is not null");
            return (Criteria) this;
        }

        public Criteria andUpd_deEqualTo(Date value) {
            addCriterion("UPD_DE =", value, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deNotEqualTo(Date value) {
            addCriterion("UPD_DE <>", value, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deGreaterThan(Date value) {
            addCriterion("UPD_DE >", value, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deGreaterThanOrEqualTo(Date value) {
            addCriterion("UPD_DE >=", value, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deLessThan(Date value) {
            addCriterion("UPD_DE <", value, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deLessThanOrEqualTo(Date value) {
            addCriterion("UPD_DE <=", value, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deIn(List<Date> values) {
            addCriterion("UPD_DE in", values, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deNotIn(List<Date> values) {
            addCriterion("UPD_DE not in", values, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deBetween(Date value1, Date value2) {
            addCriterion("UPD_DE between", value1, value2, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deNotBetween(Date value1, Date value2) {
            addCriterion("UPD_DE not between", value1, value2, "upd_de");
            return (Criteria) this;
        }

        public Criteria andDel_ynIsNull() {
            addCriterion("DEL_YN is null");
            return (Criteria) this;
        }

        public Criteria andDel_ynIsNotNull() {
            addCriterion("DEL_YN is not null");
            return (Criteria) this;
        }

        public Criteria andDel_ynEqualTo(String value) {
            addCriterion("DEL_YN =", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynNotEqualTo(String value) {
            addCriterion("DEL_YN <>", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynGreaterThan(String value) {
            addCriterion("DEL_YN >", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynGreaterThanOrEqualTo(String value) {
            addCriterion("DEL_YN >=", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynLessThan(String value) {
            addCriterion("DEL_YN <", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynLessThanOrEqualTo(String value) {
            addCriterion("DEL_YN <=", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynLike(String value) {
            addCriterion("DEL_YN like", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynNotLike(String value) {
            addCriterion("DEL_YN not like", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynIn(List<String> values) {
            addCriterion("DEL_YN in", values, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynNotIn(List<String> values) {
            addCriterion("DEL_YN not in", values, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynBetween(String value1, String value2) {
            addCriterion("DEL_YN between", value1, value2, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynNotBetween(String value1, String value2) {
            addCriterion("DEL_YN not between", value1, value2, "del_yn");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table REV_RPLY_LIST
     *
     * @mbg.generated do_not_delete_during_merge Sat Feb 10 13:30:32 KST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table REV_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}