package tk.tourwith.project.reply.review.model;

import java.util.Date;

public class RevRplyList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REV_RPLY_LIST.REV_RPLY_NO
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    private String rev_rply_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REV_RPLY_LIST.REV_NO
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    private String rev_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REV_RPLY_LIST.PARNTS_RPLY_NO
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    private String parnts_rply_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REV_RPLY_LIST.WRITNG_MB_NO
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    private String writng_mb_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REV_RPLY_LIST.REG_DE
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    private Date reg_de;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REV_RPLY_LIST.UPD_DE
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    private Date upd_de;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REV_RPLY_LIST.DEL_YN
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    private String del_yn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REV_RPLY_LIST.CON
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    private String con;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REV_RPLY_LIST.REV_RPLY_NO
     *
     * @return the value of REV_RPLY_LIST.REV_RPLY_NO
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    public String getRev_rply_no() {
        return rev_rply_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REV_RPLY_LIST.REV_RPLY_NO
     *
     * @param rev_rply_no the value for REV_RPLY_LIST.REV_RPLY_NO
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    public void setRev_rply_no(String rev_rply_no) {
        this.rev_rply_no = rev_rply_no == null ? null : rev_rply_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REV_RPLY_LIST.REV_NO
     *
     * @return the value of REV_RPLY_LIST.REV_NO
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    public String getRev_no() {
        return rev_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REV_RPLY_LIST.REV_NO
     *
     * @param rev_no the value for REV_RPLY_LIST.REV_NO
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    public void setRev_no(String rev_no) {
        this.rev_no = rev_no == null ? null : rev_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REV_RPLY_LIST.PARNTS_RPLY_NO
     *
     * @return the value of REV_RPLY_LIST.PARNTS_RPLY_NO
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    public String getParnts_rply_no() {
        return parnts_rply_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REV_RPLY_LIST.PARNTS_RPLY_NO
     *
     * @param parnts_rply_no the value for REV_RPLY_LIST.PARNTS_RPLY_NO
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    public void setParnts_rply_no(String parnts_rply_no) {
        this.parnts_rply_no = parnts_rply_no == null ? null : parnts_rply_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REV_RPLY_LIST.WRITNG_MB_NO
     *
     * @return the value of REV_RPLY_LIST.WRITNG_MB_NO
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    public String getWritng_mb_no() {
        return writng_mb_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REV_RPLY_LIST.WRITNG_MB_NO
     *
     * @param writng_mb_no the value for REV_RPLY_LIST.WRITNG_MB_NO
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    public void setWritng_mb_no(String writng_mb_no) {
        this.writng_mb_no = writng_mb_no == null ? null : writng_mb_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REV_RPLY_LIST.REG_DE
     *
     * @return the value of REV_RPLY_LIST.REG_DE
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    public Date getReg_de() {
        return reg_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REV_RPLY_LIST.REG_DE
     *
     * @param reg_de the value for REV_RPLY_LIST.REG_DE
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    public void setReg_de(Date reg_de) {
        this.reg_de = reg_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REV_RPLY_LIST.UPD_DE
     *
     * @return the value of REV_RPLY_LIST.UPD_DE
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    public Date getUpd_de() {
        return upd_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REV_RPLY_LIST.UPD_DE
     *
     * @param upd_de the value for REV_RPLY_LIST.UPD_DE
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    public void setUpd_de(Date upd_de) {
        this.upd_de = upd_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REV_RPLY_LIST.DEL_YN
     *
     * @return the value of REV_RPLY_LIST.DEL_YN
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    public String getDel_yn() {
        return del_yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REV_RPLY_LIST.DEL_YN
     *
     * @param del_yn the value for REV_RPLY_LIST.DEL_YN
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    public void setDel_yn(String del_yn) {
        this.del_yn = del_yn == null ? null : del_yn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REV_RPLY_LIST.CON
     *
     * @return the value of REV_RPLY_LIST.CON
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    public String getCon() {
        return con;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REV_RPLY_LIST.CON
     *
     * @param con the value for REV_RPLY_LIST.CON
     *
     * @mbg.generated Sat Feb 10 13:30:32 KST 2018
     */
    public void setCon(String con) {
        this.con = con == null ? null : con.trim();
    }
}