package tk.tourwith.project.crew.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class CrListExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CR_LIST
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CR_LIST
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CR_LIST
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_LIST
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public CrListExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_LIST
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_LIST
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_LIST
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_LIST
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_LIST
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_LIST
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_LIST
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_LIST
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_LIST
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_LIST
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CR_LIST
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andCr_noIsNull() {
            addCriterion("CR_NO is null");
            return (Criteria) this;
        }

        public Criteria andCr_noIsNotNull() {
            addCriterion("CR_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCr_noEqualTo(String value) {
            addCriterion("CR_NO =", value, "cr_no");
            return (Criteria) this;
        }

        public Criteria andCr_noNotEqualTo(String value) {
            addCriterion("CR_NO <>", value, "cr_no");
            return (Criteria) this;
        }

        public Criteria andCr_noGreaterThan(String value) {
            addCriterion("CR_NO >", value, "cr_no");
            return (Criteria) this;
        }

        public Criteria andCr_noGreaterThanOrEqualTo(String value) {
            addCriterion("CR_NO >=", value, "cr_no");
            return (Criteria) this;
        }

        public Criteria andCr_noLessThan(String value) {
            addCriterion("CR_NO <", value, "cr_no");
            return (Criteria) this;
        }

        public Criteria andCr_noLessThanOrEqualTo(String value) {
            addCriterion("CR_NO <=", value, "cr_no");
            return (Criteria) this;
        }

        public Criteria andCr_noLike(String value) {
            addCriterion("CR_NO like", value, "cr_no");
            return (Criteria) this;
        }

        public Criteria andCr_noNotLike(String value) {
            addCriterion("CR_NO not like", value, "cr_no");
            return (Criteria) this;
        }

        public Criteria andCr_noIn(List<String> values) {
            addCriterion("CR_NO in", values, "cr_no");
            return (Criteria) this;
        }

        public Criteria andCr_noNotIn(List<String> values) {
            addCriterion("CR_NO not in", values, "cr_no");
            return (Criteria) this;
        }

        public Criteria andCr_noBetween(String value1, String value2) {
            addCriterion("CR_NO between", value1, value2, "cr_no");
            return (Criteria) this;
        }

        public Criteria andCr_noNotBetween(String value1, String value2) {
            addCriterion("CR_NO not between", value1, value2, "cr_no");
            return (Criteria) this;
        }

        public Criteria andCr_sjIsNull() {
            addCriterion("CR_SJ is null");
            return (Criteria) this;
        }

        public Criteria andCr_sjIsNotNull() {
            addCriterion("CR_SJ is not null");
            return (Criteria) this;
        }

        public Criteria andCr_sjEqualTo(String value) {
            addCriterion("CR_SJ =", value, "cr_sj");
            return (Criteria) this;
        }

        public Criteria andCr_sjNotEqualTo(String value) {
            addCriterion("CR_SJ <>", value, "cr_sj");
            return (Criteria) this;
        }

        public Criteria andCr_sjGreaterThan(String value) {
            addCriterion("CR_SJ >", value, "cr_sj");
            return (Criteria) this;
        }

        public Criteria andCr_sjGreaterThanOrEqualTo(String value) {
            addCriterion("CR_SJ >=", value, "cr_sj");
            return (Criteria) this;
        }

        public Criteria andCr_sjLessThan(String value) {
            addCriterion("CR_SJ <", value, "cr_sj");
            return (Criteria) this;
        }

        public Criteria andCr_sjLessThanOrEqualTo(String value) {
            addCriterion("CR_SJ <=", value, "cr_sj");
            return (Criteria) this;
        }

        public Criteria andCr_sjLike(String value) {
            addCriterion("CR_SJ like", value, "cr_sj");
            return (Criteria) this;
        }

        public Criteria andCr_sjNotLike(String value) {
            addCriterion("CR_SJ not like", value, "cr_sj");
            return (Criteria) this;
        }

        public Criteria andCr_sjIn(List<String> values) {
            addCriterion("CR_SJ in", values, "cr_sj");
            return (Criteria) this;
        }

        public Criteria andCr_sjNotIn(List<String> values) {
            addCriterion("CR_SJ not in", values, "cr_sj");
            return (Criteria) this;
        }

        public Criteria andCr_sjBetween(String value1, String value2) {
            addCriterion("CR_SJ between", value1, value2, "cr_sj");
            return (Criteria) this;
        }

        public Criteria andCr_sjNotBetween(String value1, String value2) {
            addCriterion("CR_SJ not between", value1, value2, "cr_sj");
            return (Criteria) this;
        }

        public Criteria andThemaIsNull() {
            addCriterion("THEMA is null");
            return (Criteria) this;
        }

        public Criteria andThemaIsNotNull() {
            addCriterion("THEMA is not null");
            return (Criteria) this;
        }

        public Criteria andThemaEqualTo(String value) {
            addCriterion("THEMA =", value, "thema");
            return (Criteria) this;
        }

        public Criteria andThemaNotEqualTo(String value) {
            addCriterion("THEMA <>", value, "thema");
            return (Criteria) this;
        }

        public Criteria andThemaGreaterThan(String value) {
            addCriterion("THEMA >", value, "thema");
            return (Criteria) this;
        }

        public Criteria andThemaGreaterThanOrEqualTo(String value) {
            addCriterion("THEMA >=", value, "thema");
            return (Criteria) this;
        }

        public Criteria andThemaLessThan(String value) {
            addCriterion("THEMA <", value, "thema");
            return (Criteria) this;
        }

        public Criteria andThemaLessThanOrEqualTo(String value) {
            addCriterion("THEMA <=", value, "thema");
            return (Criteria) this;
        }

        public Criteria andThemaLike(String value) {
            addCriterion("THEMA like", value, "thema");
            return (Criteria) this;
        }

        public Criteria andThemaNotLike(String value) {
            addCriterion("THEMA not like", value, "thema");
            return (Criteria) this;
        }

        public Criteria andThemaIn(List<String> values) {
            addCriterion("THEMA in", values, "thema");
            return (Criteria) this;
        }

        public Criteria andThemaNotIn(List<String> values) {
            addCriterion("THEMA not in", values, "thema");
            return (Criteria) this;
        }

        public Criteria andThemaBetween(String value1, String value2) {
            addCriterion("THEMA between", value1, value2, "thema");
            return (Criteria) this;
        }

        public Criteria andThemaNotBetween(String value1, String value2) {
            addCriterion("THEMA not between", value1, value2, "thema");
            return (Criteria) this;
        }

        public Criteria andMain_coursIsNull() {
            addCriterion("MAIN_COURS is null");
            return (Criteria) this;
        }

        public Criteria andMain_coursIsNotNull() {
            addCriterion("MAIN_COURS is not null");
            return (Criteria) this;
        }

        public Criteria andMain_coursEqualTo(String value) {
            addCriterion("MAIN_COURS =", value, "main_cours");
            return (Criteria) this;
        }

        public Criteria andMain_coursNotEqualTo(String value) {
            addCriterion("MAIN_COURS <>", value, "main_cours");
            return (Criteria) this;
        }

        public Criteria andMain_coursGreaterThan(String value) {
            addCriterion("MAIN_COURS >", value, "main_cours");
            return (Criteria) this;
        }

        public Criteria andMain_coursGreaterThanOrEqualTo(String value) {
            addCriterion("MAIN_COURS >=", value, "main_cours");
            return (Criteria) this;
        }

        public Criteria andMain_coursLessThan(String value) {
            addCriterion("MAIN_COURS <", value, "main_cours");
            return (Criteria) this;
        }

        public Criteria andMain_coursLessThanOrEqualTo(String value) {
            addCriterion("MAIN_COURS <=", value, "main_cours");
            return (Criteria) this;
        }

        public Criteria andMain_coursLike(String value) {
            addCriterion("MAIN_COURS like", value, "main_cours");
            return (Criteria) this;
        }

        public Criteria andMain_coursNotLike(String value) {
            addCriterion("MAIN_COURS not like", value, "main_cours");
            return (Criteria) this;
        }

        public Criteria andMain_coursIn(List<String> values) {
            addCriterion("MAIN_COURS in", values, "main_cours");
            return (Criteria) this;
        }

        public Criteria andMain_coursNotIn(List<String> values) {
            addCriterion("MAIN_COURS not in", values, "main_cours");
            return (Criteria) this;
        }

        public Criteria andMain_coursBetween(String value1, String value2) {
            addCriterion("MAIN_COURS between", value1, value2, "main_cours");
            return (Criteria) this;
        }

        public Criteria andMain_coursNotBetween(String value1, String value2) {
            addCriterion("MAIN_COURS not between", value1, value2, "main_cours");
            return (Criteria) this;
        }

        public Criteria andDetail_trplcIsNull() {
            addCriterion("DETAIL_TRPLC is null");
            return (Criteria) this;
        }

        public Criteria andDetail_trplcIsNotNull() {
            addCriterion("DETAIL_TRPLC is not null");
            return (Criteria) this;
        }

        public Criteria andDetail_trplcEqualTo(String value) {
            addCriterion("DETAIL_TRPLC =", value, "detail_trplc");
            return (Criteria) this;
        }

        public Criteria andDetail_trplcNotEqualTo(String value) {
            addCriterion("DETAIL_TRPLC <>", value, "detail_trplc");
            return (Criteria) this;
        }

        public Criteria andDetail_trplcGreaterThan(String value) {
            addCriterion("DETAIL_TRPLC >", value, "detail_trplc");
            return (Criteria) this;
        }

        public Criteria andDetail_trplcGreaterThanOrEqualTo(String value) {
            addCriterion("DETAIL_TRPLC >=", value, "detail_trplc");
            return (Criteria) this;
        }

        public Criteria andDetail_trplcLessThan(String value) {
            addCriterion("DETAIL_TRPLC <", value, "detail_trplc");
            return (Criteria) this;
        }

        public Criteria andDetail_trplcLessThanOrEqualTo(String value) {
            addCriterion("DETAIL_TRPLC <=", value, "detail_trplc");
            return (Criteria) this;
        }

        public Criteria andDetail_trplcLike(String value) {
            addCriterion("DETAIL_TRPLC like", value, "detail_trplc");
            return (Criteria) this;
        }

        public Criteria andDetail_trplcNotLike(String value) {
            addCriterion("DETAIL_TRPLC not like", value, "detail_trplc");
            return (Criteria) this;
        }

        public Criteria andDetail_trplcIn(List<String> values) {
            addCriterion("DETAIL_TRPLC in", values, "detail_trplc");
            return (Criteria) this;
        }

        public Criteria andDetail_trplcNotIn(List<String> values) {
            addCriterion("DETAIL_TRPLC not in", values, "detail_trplc");
            return (Criteria) this;
        }

        public Criteria andDetail_trplcBetween(String value1, String value2) {
            addCriterion("DETAIL_TRPLC between", value1, value2, "detail_trplc");
            return (Criteria) this;
        }

        public Criteria andDetail_trplcNotBetween(String value1, String value2) {
            addCriterion("DETAIL_TRPLC not between", value1, value2, "detail_trplc");
            return (Criteria) this;
        }

        public Criteria andDeprdeIsNull() {
            addCriterion("DEPRDE is null");
            return (Criteria) this;
        }

        public Criteria andDeprdeIsNotNull() {
            addCriterion("DEPRDE is not null");
            return (Criteria) this;
        }

        public Criteria andDeprdeEqualTo(Date value) {
            addCriterionForJDBCDate("DEPRDE =", value, "deprde");
            return (Criteria) this;
        }

        public Criteria andDeprdeNotEqualTo(Date value) {
            addCriterionForJDBCDate("DEPRDE <>", value, "deprde");
            return (Criteria) this;
        }

        public Criteria andDeprdeGreaterThan(Date value) {
            addCriterionForJDBCDate("DEPRDE >", value, "deprde");
            return (Criteria) this;
        }

        public Criteria andDeprdeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("DEPRDE >=", value, "deprde");
            return (Criteria) this;
        }

        public Criteria andDeprdeLessThan(Date value) {
            addCriterionForJDBCDate("DEPRDE <", value, "deprde");
            return (Criteria) this;
        }

        public Criteria andDeprdeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("DEPRDE <=", value, "deprde");
            return (Criteria) this;
        }

        public Criteria andDeprdeIn(List<Date> values) {
            addCriterionForJDBCDate("DEPRDE in", values, "deprde");
            return (Criteria) this;
        }

        public Criteria andDeprdeNotIn(List<Date> values) {
            addCriterionForJDBCDate("DEPRDE not in", values, "deprde");
            return (Criteria) this;
        }

        public Criteria andDeprdeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("DEPRDE between", value1, value2, "deprde");
            return (Criteria) this;
        }

        public Criteria andDeprdeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("DEPRDE not between", value1, value2, "deprde");
            return (Criteria) this;
        }

        public Criteria andArvldeIsNull() {
            addCriterion("ARVLDE is null");
            return (Criteria) this;
        }

        public Criteria andArvldeIsNotNull() {
            addCriterion("ARVLDE is not null");
            return (Criteria) this;
        }

        public Criteria andArvldeEqualTo(Date value) {
            addCriterionForJDBCDate("ARVLDE =", value, "arvlde");
            return (Criteria) this;
        }

        public Criteria andArvldeNotEqualTo(Date value) {
            addCriterionForJDBCDate("ARVLDE <>", value, "arvlde");
            return (Criteria) this;
        }

        public Criteria andArvldeGreaterThan(Date value) {
            addCriterionForJDBCDate("ARVLDE >", value, "arvlde");
            return (Criteria) this;
        }

        public Criteria andArvldeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ARVLDE >=", value, "arvlde");
            return (Criteria) this;
        }

        public Criteria andArvldeLessThan(Date value) {
            addCriterionForJDBCDate("ARVLDE <", value, "arvlde");
            return (Criteria) this;
        }

        public Criteria andArvldeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ARVLDE <=", value, "arvlde");
            return (Criteria) this;
        }

        public Criteria andArvldeIn(List<Date> values) {
            addCriterionForJDBCDate("ARVLDE in", values, "arvlde");
            return (Criteria) this;
        }

        public Criteria andArvldeNotIn(List<Date> values) {
            addCriterionForJDBCDate("ARVLDE not in", values, "arvlde");
            return (Criteria) this;
        }

        public Criteria andArvldeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ARVLDE between", value1, value2, "arvlde");
            return (Criteria) this;
        }

        public Criteria andArvldeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ARVLDE not between", value1, value2, "arvlde");
            return (Criteria) this;
        }

        public Criteria andNow_male_nmprIsNull() {
            addCriterion("NOW_MALE_NMPR is null");
            return (Criteria) this;
        }

        public Criteria andNow_male_nmprIsNotNull() {
            addCriterion("NOW_MALE_NMPR is not null");
            return (Criteria) this;
        }

        public Criteria andNow_male_nmprEqualTo(Integer value) {
            addCriterion("NOW_MALE_NMPR =", value, "now_male_nmpr");
            return (Criteria) this;
        }

        public Criteria andNow_male_nmprNotEqualTo(Integer value) {
            addCriterion("NOW_MALE_NMPR <>", value, "now_male_nmpr");
            return (Criteria) this;
        }

        public Criteria andNow_male_nmprGreaterThan(Integer value) {
            addCriterion("NOW_MALE_NMPR >", value, "now_male_nmpr");
            return (Criteria) this;
        }

        public Criteria andNow_male_nmprGreaterThanOrEqualTo(Integer value) {
            addCriterion("NOW_MALE_NMPR >=", value, "now_male_nmpr");
            return (Criteria) this;
        }

        public Criteria andNow_male_nmprLessThan(Integer value) {
            addCriterion("NOW_MALE_NMPR <", value, "now_male_nmpr");
            return (Criteria) this;
        }

        public Criteria andNow_male_nmprLessThanOrEqualTo(Integer value) {
            addCriterion("NOW_MALE_NMPR <=", value, "now_male_nmpr");
            return (Criteria) this;
        }

        public Criteria andNow_male_nmprIn(List<Integer> values) {
            addCriterion("NOW_MALE_NMPR in", values, "now_male_nmpr");
            return (Criteria) this;
        }

        public Criteria andNow_male_nmprNotIn(List<Integer> values) {
            addCriterion("NOW_MALE_NMPR not in", values, "now_male_nmpr");
            return (Criteria) this;
        }

        public Criteria andNow_male_nmprBetween(Integer value1, Integer value2) {
            addCriterion("NOW_MALE_NMPR between", value1, value2, "now_male_nmpr");
            return (Criteria) this;
        }

        public Criteria andNow_male_nmprNotBetween(Integer value1, Integer value2) {
            addCriterion("NOW_MALE_NMPR not between", value1, value2, "now_male_nmpr");
            return (Criteria) this;
        }

        public Criteria andMale_nmprIsNull() {
            addCriterion("MALE_NMPR is null");
            return (Criteria) this;
        }

        public Criteria andMale_nmprIsNotNull() {
            addCriterion("MALE_NMPR is not null");
            return (Criteria) this;
        }

        public Criteria andMale_nmprEqualTo(Integer value) {
            addCriterion("MALE_NMPR =", value, "male_nmpr");
            return (Criteria) this;
        }

        public Criteria andMale_nmprNotEqualTo(Integer value) {
            addCriterion("MALE_NMPR <>", value, "male_nmpr");
            return (Criteria) this;
        }

        public Criteria andMale_nmprGreaterThan(Integer value) {
            addCriterion("MALE_NMPR >", value, "male_nmpr");
            return (Criteria) this;
        }

        public Criteria andMale_nmprGreaterThanOrEqualTo(Integer value) {
            addCriterion("MALE_NMPR >=", value, "male_nmpr");
            return (Criteria) this;
        }

        public Criteria andMale_nmprLessThan(Integer value) {
            addCriterion("MALE_NMPR <", value, "male_nmpr");
            return (Criteria) this;
        }

        public Criteria andMale_nmprLessThanOrEqualTo(Integer value) {
            addCriterion("MALE_NMPR <=", value, "male_nmpr");
            return (Criteria) this;
        }

        public Criteria andMale_nmprIn(List<Integer> values) {
            addCriterion("MALE_NMPR in", values, "male_nmpr");
            return (Criteria) this;
        }

        public Criteria andMale_nmprNotIn(List<Integer> values) {
            addCriterion("MALE_NMPR not in", values, "male_nmpr");
            return (Criteria) this;
        }

        public Criteria andMale_nmprBetween(Integer value1, Integer value2) {
            addCriterion("MALE_NMPR between", value1, value2, "male_nmpr");
            return (Criteria) this;
        }

        public Criteria andMale_nmprNotBetween(Integer value1, Integer value2) {
            addCriterion("MALE_NMPR not between", value1, value2, "male_nmpr");
            return (Criteria) this;
        }

        public Criteria andFemale_nmprIsNull() {
            addCriterion("FEMALE_NMPR is null");
            return (Criteria) this;
        }

        public Criteria andFemale_nmprIsNotNull() {
            addCriterion("FEMALE_NMPR is not null");
            return (Criteria) this;
        }

        public Criteria andFemale_nmprEqualTo(Integer value) {
            addCriterion("FEMALE_NMPR =", value, "female_nmpr");
            return (Criteria) this;
        }

        public Criteria andFemale_nmprNotEqualTo(Integer value) {
            addCriterion("FEMALE_NMPR <>", value, "female_nmpr");
            return (Criteria) this;
        }

        public Criteria andFemale_nmprGreaterThan(Integer value) {
            addCriterion("FEMALE_NMPR >", value, "female_nmpr");
            return (Criteria) this;
        }

        public Criteria andFemale_nmprGreaterThanOrEqualTo(Integer value) {
            addCriterion("FEMALE_NMPR >=", value, "female_nmpr");
            return (Criteria) this;
        }

        public Criteria andFemale_nmprLessThan(Integer value) {
            addCriterion("FEMALE_NMPR <", value, "female_nmpr");
            return (Criteria) this;
        }

        public Criteria andFemale_nmprLessThanOrEqualTo(Integer value) {
            addCriterion("FEMALE_NMPR <=", value, "female_nmpr");
            return (Criteria) this;
        }

        public Criteria andFemale_nmprIn(List<Integer> values) {
            addCriterion("FEMALE_NMPR in", values, "female_nmpr");
            return (Criteria) this;
        }

        public Criteria andFemale_nmprNotIn(List<Integer> values) {
            addCriterion("FEMALE_NMPR not in", values, "female_nmpr");
            return (Criteria) this;
        }

        public Criteria andFemale_nmprBetween(Integer value1, Integer value2) {
            addCriterion("FEMALE_NMPR between", value1, value2, "female_nmpr");
            return (Criteria) this;
        }

        public Criteria andFemale_nmprNotBetween(Integer value1, Integer value2) {
            addCriterion("FEMALE_NMPR not between", value1, value2, "female_nmpr");
            return (Criteria) this;
        }

        public Criteria andNow_female_nmprIsNull() {
            addCriterion("NOW_FEMALE_NMPR is null");
            return (Criteria) this;
        }

        public Criteria andNow_female_nmprIsNotNull() {
            addCriterion("NOW_FEMALE_NMPR is not null");
            return (Criteria) this;
        }

        public Criteria andNow_female_nmprEqualTo(Integer value) {
            addCriterion("NOW_FEMALE_NMPR =", value, "now_female_nmpr");
            return (Criteria) this;
        }

        public Criteria andNow_female_nmprNotEqualTo(Integer value) {
            addCriterion("NOW_FEMALE_NMPR <>", value, "now_female_nmpr");
            return (Criteria) this;
        }

        public Criteria andNow_female_nmprGreaterThan(Integer value) {
            addCriterion("NOW_FEMALE_NMPR >", value, "now_female_nmpr");
            return (Criteria) this;
        }

        public Criteria andNow_female_nmprGreaterThanOrEqualTo(Integer value) {
            addCriterion("NOW_FEMALE_NMPR >=", value, "now_female_nmpr");
            return (Criteria) this;
        }

        public Criteria andNow_female_nmprLessThan(Integer value) {
            addCriterion("NOW_FEMALE_NMPR <", value, "now_female_nmpr");
            return (Criteria) this;
        }

        public Criteria andNow_female_nmprLessThanOrEqualTo(Integer value) {
            addCriterion("NOW_FEMALE_NMPR <=", value, "now_female_nmpr");
            return (Criteria) this;
        }

        public Criteria andNow_female_nmprIn(List<Integer> values) {
            addCriterion("NOW_FEMALE_NMPR in", values, "now_female_nmpr");
            return (Criteria) this;
        }

        public Criteria andNow_female_nmprNotIn(List<Integer> values) {
            addCriterion("NOW_FEMALE_NMPR not in", values, "now_female_nmpr");
            return (Criteria) this;
        }

        public Criteria andNow_female_nmprBetween(Integer value1, Integer value2) {
            addCriterion("NOW_FEMALE_NMPR between", value1, value2, "now_female_nmpr");
            return (Criteria) this;
        }

        public Criteria andNow_female_nmprNotBetween(Integer value1, Integer value2) {
            addCriterion("NOW_FEMALE_NMPR not between", value1, value2, "now_female_nmpr");
            return (Criteria) this;
        }

        public Criteria andReg_deIsNull() {
            addCriterion("REG_DE is null");
            return (Criteria) this;
        }

        public Criteria andReg_deIsNotNull() {
            addCriterion("REG_DE is not null");
            return (Criteria) this;
        }

        public Criteria andReg_deEqualTo(Date value) {
            addCriterion("REG_DE =", value, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deNotEqualTo(Date value) {
            addCriterion("REG_DE <>", value, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deGreaterThan(Date value) {
            addCriterion("REG_DE >", value, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deGreaterThanOrEqualTo(Date value) {
            addCriterion("REG_DE >=", value, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deLessThan(Date value) {
            addCriterion("REG_DE <", value, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deLessThanOrEqualTo(Date value) {
            addCriterion("REG_DE <=", value, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deIn(List<Date> values) {
            addCriterion("REG_DE in", values, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deNotIn(List<Date> values) {
            addCriterion("REG_DE not in", values, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deBetween(Date value1, Date value2) {
            addCriterion("REG_DE between", value1, value2, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deNotBetween(Date value1, Date value2) {
            addCriterion("REG_DE not between", value1, value2, "reg_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deIsNull() {
            addCriterion("UPD_DE is null");
            return (Criteria) this;
        }

        public Criteria andUpd_deIsNotNull() {
            addCriterion("UPD_DE is not null");
            return (Criteria) this;
        }

        public Criteria andUpd_deEqualTo(Date value) {
            addCriterion("UPD_DE =", value, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deNotEqualTo(Date value) {
            addCriterion("UPD_DE <>", value, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deGreaterThan(Date value) {
            addCriterion("UPD_DE >", value, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deGreaterThanOrEqualTo(Date value) {
            addCriterion("UPD_DE >=", value, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deLessThan(Date value) {
            addCriterion("UPD_DE <", value, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deLessThanOrEqualTo(Date value) {
            addCriterion("UPD_DE <=", value, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deIn(List<Date> values) {
            addCriterion("UPD_DE in", values, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deNotIn(List<Date> values) {
            addCriterion("UPD_DE not in", values, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deBetween(Date value1, Date value2) {
            addCriterion("UPD_DE between", value1, value2, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deNotBetween(Date value1, Date value2) {
            addCriterion("UPD_DE not between", value1, value2, "upd_de");
            return (Criteria) this;
        }

        public Criteria andDel_ynIsNull() {
            addCriterion("DEL_YN is null");
            return (Criteria) this;
        }

        public Criteria andDel_ynIsNotNull() {
            addCriterion("DEL_YN is not null");
            return (Criteria) this;
        }

        public Criteria andDel_ynEqualTo(String value) {
            addCriterion("DEL_YN =", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynNotEqualTo(String value) {
            addCriterion("DEL_YN <>", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynGreaterThan(String value) {
            addCriterion("DEL_YN >", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynGreaterThanOrEqualTo(String value) {
            addCriterion("DEL_YN >=", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynLessThan(String value) {
            addCriterion("DEL_YN <", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynLessThanOrEqualTo(String value) {
            addCriterion("DEL_YN <=", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynLike(String value) {
            addCriterion("DEL_YN like", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynNotLike(String value) {
            addCriterion("DEL_YN not like", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynIn(List<String> values) {
            addCriterion("DEL_YN in", values, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynNotIn(List<String> values) {
            addCriterion("DEL_YN not in", values, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynBetween(String value1, String value2) {
            addCriterion("DEL_YN between", value1, value2, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynNotBetween(String value1, String value2) {
            addCriterion("DEL_YN not between", value1, value2, "del_yn");
            return (Criteria) this;
        }

        public Criteria andCr_leadr_mb_noIsNull() {
            addCriterion("CR_LEADR_MB_NO is null");
            return (Criteria) this;
        }

        public Criteria andCr_leadr_mb_noIsNotNull() {
            addCriterion("CR_LEADR_MB_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCr_leadr_mb_noEqualTo(String value) {
            addCriterion("CR_LEADR_MB_NO =", value, "cr_leadr_mb_no");
            return (Criteria) this;
        }

        public Criteria andCr_leadr_mb_noNotEqualTo(String value) {
            addCriterion("CR_LEADR_MB_NO <>", value, "cr_leadr_mb_no");
            return (Criteria) this;
        }

        public Criteria andCr_leadr_mb_noGreaterThan(String value) {
            addCriterion("CR_LEADR_MB_NO >", value, "cr_leadr_mb_no");
            return (Criteria) this;
        }

        public Criteria andCr_leadr_mb_noGreaterThanOrEqualTo(String value) {
            addCriterion("CR_LEADR_MB_NO >=", value, "cr_leadr_mb_no");
            return (Criteria) this;
        }

        public Criteria andCr_leadr_mb_noLessThan(String value) {
            addCriterion("CR_LEADR_MB_NO <", value, "cr_leadr_mb_no");
            return (Criteria) this;
        }

        public Criteria andCr_leadr_mb_noLessThanOrEqualTo(String value) {
            addCriterion("CR_LEADR_MB_NO <=", value, "cr_leadr_mb_no");
            return (Criteria) this;
        }

        public Criteria andCr_leadr_mb_noLike(String value) {
            addCriterion("CR_LEADR_MB_NO like", value, "cr_leadr_mb_no");
            return (Criteria) this;
        }

        public Criteria andCr_leadr_mb_noNotLike(String value) {
            addCriterion("CR_LEADR_MB_NO not like", value, "cr_leadr_mb_no");
            return (Criteria) this;
        }

        public Criteria andCr_leadr_mb_noIn(List<String> values) {
            addCriterion("CR_LEADR_MB_NO in", values, "cr_leadr_mb_no");
            return (Criteria) this;
        }

        public Criteria andCr_leadr_mb_noNotIn(List<String> values) {
            addCriterion("CR_LEADR_MB_NO not in", values, "cr_leadr_mb_no");
            return (Criteria) this;
        }

        public Criteria andCr_leadr_mb_noBetween(String value1, String value2) {
            addCriterion("CR_LEADR_MB_NO between", value1, value2, "cr_leadr_mb_no");
            return (Criteria) this;
        }

        public Criteria andCr_leadr_mb_noNotBetween(String value1, String value2) {
            addCriterion("CR_LEADR_MB_NO not between", value1, value2, "cr_leadr_mb_no");
            return (Criteria) this;
        }

        public Criteria andTrplc_noIsNull() {
            addCriterion("TRPLC_NO is null");
            return (Criteria) this;
        }

        public Criteria andTrplc_noIsNotNull() {
            addCriterion("TRPLC_NO is not null");
            return (Criteria) this;
        }

        public Criteria andTrplc_noEqualTo(String value) {
            addCriterion("TRPLC_NO =", value, "trplc_no");
            return (Criteria) this;
        }

        public Criteria andTrplc_noNotEqualTo(String value) {
            addCriterion("TRPLC_NO <>", value, "trplc_no");
            return (Criteria) this;
        }

        public Criteria andTrplc_noGreaterThan(String value) {
            addCriterion("TRPLC_NO >", value, "trplc_no");
            return (Criteria) this;
        }

        public Criteria andTrplc_noGreaterThanOrEqualTo(String value) {
            addCriterion("TRPLC_NO >=", value, "trplc_no");
            return (Criteria) this;
        }

        public Criteria andTrplc_noLessThan(String value) {
            addCriterion("TRPLC_NO <", value, "trplc_no");
            return (Criteria) this;
        }

        public Criteria andTrplc_noLessThanOrEqualTo(String value) {
            addCriterion("TRPLC_NO <=", value, "trplc_no");
            return (Criteria) this;
        }

        public Criteria andTrplc_noLike(String value) {
            addCriterion("TRPLC_NO like", value, "trplc_no");
            return (Criteria) this;
        }

        public Criteria andTrplc_noNotLike(String value) {
            addCriterion("TRPLC_NO not like", value, "trplc_no");
            return (Criteria) this;
        }

        public Criteria andTrplc_noIn(List<String> values) {
            addCriterion("TRPLC_NO in", values, "trplc_no");
            return (Criteria) this;
        }

        public Criteria andTrplc_noNotIn(List<String> values) {
            addCriterion("TRPLC_NO not in", values, "trplc_no");
            return (Criteria) this;
        }

        public Criteria andTrplc_noBetween(String value1, String value2) {
            addCriterion("TRPLC_NO between", value1, value2, "trplc_no");
            return (Criteria) this;
        }

        public Criteria andTrplc_noNotBetween(String value1, String value2) {
            addCriterion("TRPLC_NO not between", value1, value2, "trplc_no");
            return (Criteria) this;
        }

        public Criteria andRcrit_sttusIsNull() {
            addCriterion("RCRIT_STTUS is null");
            return (Criteria) this;
        }

        public Criteria andRcrit_sttusIsNotNull() {
            addCriterion("RCRIT_STTUS is not null");
            return (Criteria) this;
        }

        public Criteria andRcrit_sttusEqualTo(String value) {
            addCriterion("RCRIT_STTUS =", value, "rcrit_sttus");
            return (Criteria) this;
        }

        public Criteria andRcrit_sttusNotEqualTo(String value) {
            addCriterion("RCRIT_STTUS <>", value, "rcrit_sttus");
            return (Criteria) this;
        }

        public Criteria andRcrit_sttusGreaterThan(String value) {
            addCriterion("RCRIT_STTUS >", value, "rcrit_sttus");
            return (Criteria) this;
        }

        public Criteria andRcrit_sttusGreaterThanOrEqualTo(String value) {
            addCriterion("RCRIT_STTUS >=", value, "rcrit_sttus");
            return (Criteria) this;
        }

        public Criteria andRcrit_sttusLessThan(String value) {
            addCriterion("RCRIT_STTUS <", value, "rcrit_sttus");
            return (Criteria) this;
        }

        public Criteria andRcrit_sttusLessThanOrEqualTo(String value) {
            addCriterion("RCRIT_STTUS <=", value, "rcrit_sttus");
            return (Criteria) this;
        }

        public Criteria andRcrit_sttusLike(String value) {
            addCriterion("RCRIT_STTUS like", value, "rcrit_sttus");
            return (Criteria) this;
        }

        public Criteria andRcrit_sttusNotLike(String value) {
            addCriterion("RCRIT_STTUS not like", value, "rcrit_sttus");
            return (Criteria) this;
        }

        public Criteria andRcrit_sttusIn(List<String> values) {
            addCriterion("RCRIT_STTUS in", values, "rcrit_sttus");
            return (Criteria) this;
        }

        public Criteria andRcrit_sttusNotIn(List<String> values) {
            addCriterion("RCRIT_STTUS not in", values, "rcrit_sttus");
            return (Criteria) this;
        }

        public Criteria andRcrit_sttusBetween(String value1, String value2) {
            addCriterion("RCRIT_STTUS between", value1, value2, "rcrit_sttus");
            return (Criteria) this;
        }

        public Criteria andRcrit_sttusNotBetween(String value1, String value2) {
            addCriterion("RCRIT_STTUS not between", value1, value2, "rcrit_sttus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CR_LIST
     *
     * @mbg.generated do_not_delete_during_merge Sat Feb 10 13:37:29 KST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CR_LIST
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}