package tk.tourwith.project.crew.model;

import java.util.Date;

public class CrList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_LIST.CR_NO
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    private String cr_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_LIST.CR_SJ
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    private String cr_sj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_LIST.THEMA
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    private String thema;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_LIST.MAIN_COURS
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    private String main_cours;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_LIST.DETAIL_TRPLC
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    private String detail_trplc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_LIST.DEPRDE
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    private Date deprde;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_LIST.ARVLDE
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    private Date arvlde;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_LIST.NOW_MALE_NMPR
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    private Integer now_male_nmpr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_LIST.MALE_NMPR
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    private Integer male_nmpr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_LIST.FEMALE_NMPR
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    private Integer female_nmpr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_LIST.NOW_FEMALE_NMPR
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    private Integer now_female_nmpr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_LIST.REG_DE
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    private Date reg_de;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_LIST.UPD_DE
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    private Date upd_de;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_LIST.DEL_YN
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    private String del_yn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_LIST.CR_LEADR_MB_NO
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    private String cr_leadr_mb_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_LIST.TRPLC_NO
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    private String trplc_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_LIST.RCRIT_STTUS
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    private String rcrit_sttus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_LIST.PRTXT
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    private String prtxt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_LIST.CR_NO
     *
     * @return the value of CR_LIST.CR_NO
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public String getCr_no() {
        return cr_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_LIST.CR_NO
     *
     * @param cr_no the value for CR_LIST.CR_NO
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public void setCr_no(String cr_no) {
        this.cr_no = cr_no == null ? null : cr_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_LIST.CR_SJ
     *
     * @return the value of CR_LIST.CR_SJ
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public String getCr_sj() {
        return cr_sj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_LIST.CR_SJ
     *
     * @param cr_sj the value for CR_LIST.CR_SJ
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public void setCr_sj(String cr_sj) {
        this.cr_sj = cr_sj == null ? null : cr_sj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_LIST.THEMA
     *
     * @return the value of CR_LIST.THEMA
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public String getThema() {
        return thema;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_LIST.THEMA
     *
     * @param thema the value for CR_LIST.THEMA
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public void setThema(String thema) {
        this.thema = thema == null ? null : thema.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_LIST.MAIN_COURS
     *
     * @return the value of CR_LIST.MAIN_COURS
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public String getMain_cours() {
        return main_cours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_LIST.MAIN_COURS
     *
     * @param main_cours the value for CR_LIST.MAIN_COURS
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public void setMain_cours(String main_cours) {
        this.main_cours = main_cours == null ? null : main_cours.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_LIST.DETAIL_TRPLC
     *
     * @return the value of CR_LIST.DETAIL_TRPLC
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public String getDetail_trplc() {
        return detail_trplc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_LIST.DETAIL_TRPLC
     *
     * @param detail_trplc the value for CR_LIST.DETAIL_TRPLC
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public void setDetail_trplc(String detail_trplc) {
        this.detail_trplc = detail_trplc == null ? null : detail_trplc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_LIST.DEPRDE
     *
     * @return the value of CR_LIST.DEPRDE
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public Date getDeprde() {
        return deprde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_LIST.DEPRDE
     *
     * @param deprde the value for CR_LIST.DEPRDE
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public void setDeprde(Date deprde) {
        this.deprde = deprde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_LIST.ARVLDE
     *
     * @return the value of CR_LIST.ARVLDE
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public Date getArvlde() {
        return arvlde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_LIST.ARVLDE
     *
     * @param arvlde the value for CR_LIST.ARVLDE
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public void setArvlde(Date arvlde) {
        this.arvlde = arvlde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_LIST.NOW_MALE_NMPR
     *
     * @return the value of CR_LIST.NOW_MALE_NMPR
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public Integer getNow_male_nmpr() {
        return now_male_nmpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_LIST.NOW_MALE_NMPR
     *
     * @param now_male_nmpr the value for CR_LIST.NOW_MALE_NMPR
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public void setNow_male_nmpr(Integer now_male_nmpr) {
        this.now_male_nmpr = now_male_nmpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_LIST.MALE_NMPR
     *
     * @return the value of CR_LIST.MALE_NMPR
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public Integer getMale_nmpr() {
        return male_nmpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_LIST.MALE_NMPR
     *
     * @param male_nmpr the value for CR_LIST.MALE_NMPR
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public void setMale_nmpr(Integer male_nmpr) {
        this.male_nmpr = male_nmpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_LIST.FEMALE_NMPR
     *
     * @return the value of CR_LIST.FEMALE_NMPR
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public Integer getFemale_nmpr() {
        return female_nmpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_LIST.FEMALE_NMPR
     *
     * @param female_nmpr the value for CR_LIST.FEMALE_NMPR
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public void setFemale_nmpr(Integer female_nmpr) {
        this.female_nmpr = female_nmpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_LIST.NOW_FEMALE_NMPR
     *
     * @return the value of CR_LIST.NOW_FEMALE_NMPR
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public Integer getNow_female_nmpr() {
        return now_female_nmpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_LIST.NOW_FEMALE_NMPR
     *
     * @param now_female_nmpr the value for CR_LIST.NOW_FEMALE_NMPR
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public void setNow_female_nmpr(Integer now_female_nmpr) {
        this.now_female_nmpr = now_female_nmpr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_LIST.REG_DE
     *
     * @return the value of CR_LIST.REG_DE
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public Date getReg_de() {
        return reg_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_LIST.REG_DE
     *
     * @param reg_de the value for CR_LIST.REG_DE
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public void setReg_de(Date reg_de) {
        this.reg_de = reg_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_LIST.UPD_DE
     *
     * @return the value of CR_LIST.UPD_DE
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public Date getUpd_de() {
        return upd_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_LIST.UPD_DE
     *
     * @param upd_de the value for CR_LIST.UPD_DE
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public void setUpd_de(Date upd_de) {
        this.upd_de = upd_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_LIST.DEL_YN
     *
     * @return the value of CR_LIST.DEL_YN
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public String getDel_yn() {
        return del_yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_LIST.DEL_YN
     *
     * @param del_yn the value for CR_LIST.DEL_YN
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public void setDel_yn(String del_yn) {
        this.del_yn = del_yn == null ? null : del_yn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_LIST.CR_LEADR_MB_NO
     *
     * @return the value of CR_LIST.CR_LEADR_MB_NO
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public String getCr_leadr_mb_no() {
        return cr_leadr_mb_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_LIST.CR_LEADR_MB_NO
     *
     * @param cr_leadr_mb_no the value for CR_LIST.CR_LEADR_MB_NO
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public void setCr_leadr_mb_no(String cr_leadr_mb_no) {
        this.cr_leadr_mb_no = cr_leadr_mb_no == null ? null : cr_leadr_mb_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_LIST.TRPLC_NO
     *
     * @return the value of CR_LIST.TRPLC_NO
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public String getTrplc_no() {
        return trplc_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_LIST.TRPLC_NO
     *
     * @param trplc_no the value for CR_LIST.TRPLC_NO
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public void setTrplc_no(String trplc_no) {
        this.trplc_no = trplc_no == null ? null : trplc_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_LIST.RCRIT_STTUS
     *
     * @return the value of CR_LIST.RCRIT_STTUS
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public String getRcrit_sttus() {
        return rcrit_sttus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_LIST.RCRIT_STTUS
     *
     * @param rcrit_sttus the value for CR_LIST.RCRIT_STTUS
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public void setRcrit_sttus(String rcrit_sttus) {
        this.rcrit_sttus = rcrit_sttus == null ? null : rcrit_sttus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_LIST.PRTXT
     *
     * @return the value of CR_LIST.PRTXT
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public String getPrtxt() {
        return prtxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_LIST.PRTXT
     *
     * @param prtxt the value for CR_LIST.PRTXT
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    public void setPrtxt(String prtxt) {
        this.prtxt = prtxt == null ? null : prtxt.trim();
    }
}