package tk.tourwith.project.util.file.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tk.tourwith.project.util.file.model.FileManage;
import tk.tourwith.project.util.file.model.FileManageExample;

public interface FileManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILE_MANAGE
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    long countByExample(FileManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILE_MANAGE
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    int deleteByExample(FileManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILE_MANAGE
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    int insert(FileManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILE_MANAGE
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    int insertSelective(FileManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILE_MANAGE
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    List<FileManage> selectByExampleWithBLOBs(FileManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILE_MANAGE
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    List<FileManage> selectByExample(FileManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILE_MANAGE
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    int updateByExampleSelective(@Param("record") FileManage record, @Param("example") FileManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILE_MANAGE
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") FileManage record, @Param("example") FileManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FILE_MANAGE
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    int updateByExample(@Param("record") FileManage record, @Param("example") FileManageExample example);
}