package tk.tourwith.project.util.file.model;

import java.util.Date;

public class FileManage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILE_MANAGE.FILE_NO
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    private String file_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILE_MANAGE.BBSCTT_NO
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    private String bbsctt_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILE_MANAGE.FILE_TY
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    private String file_ty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILE_MANAGE.FILE_NM
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    private String file_nm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILE_MANAGE.STRE_NM
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    private String stre_nm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILE_MANAGE.DETAIL_STRE_COURS
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    private String detail_stre_cours;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILE_MANAGE.ROOT_STRE_COURS
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    private String root_stre_cours;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILE_MANAGE.FANCY_SIZE
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    private String fancy_size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILE_MANAGE.REGISTER
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    private String register;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILE_MANAGE.TABLE_SE
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    private String tableSe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILE_MANAGE.REG_YN
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    private String regYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILE_MANAGE.REG_DE
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    private Date regDe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILE_MANAGE.FILE_SIZE
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    private String file_size;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILE_MANAGE.FILE_NO
     *
     * @return the value of FILE_MANAGE.FILE_NO
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    public String getFile_no() {
        return file_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILE_MANAGE.FILE_NO
     *
     * @param file_no the value for FILE_MANAGE.FILE_NO
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    public void setFile_no(String file_no) {
        this.file_no = file_no == null ? null : file_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILE_MANAGE.BBSCTT_NO
     *
     * @return the value of FILE_MANAGE.BBSCTT_NO
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    public String getBbsctt_no() {
        return bbsctt_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILE_MANAGE.BBSCTT_NO
     *
     * @param bbsctt_no the value for FILE_MANAGE.BBSCTT_NO
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    public void setBbsctt_no(String bbsctt_no) {
        this.bbsctt_no = bbsctt_no == null ? null : bbsctt_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILE_MANAGE.FILE_TY
     *
     * @return the value of FILE_MANAGE.FILE_TY
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    public String getFile_ty() {
        return file_ty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILE_MANAGE.FILE_TY
     *
     * @param file_ty the value for FILE_MANAGE.FILE_TY
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    public void setFile_ty(String file_ty) {
        this.file_ty = file_ty == null ? null : file_ty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILE_MANAGE.FILE_NM
     *
     * @return the value of FILE_MANAGE.FILE_NM
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    public String getFile_nm() {
        return file_nm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILE_MANAGE.FILE_NM
     *
     * @param file_nm the value for FILE_MANAGE.FILE_NM
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    public void setFile_nm(String file_nm) {
        this.file_nm = file_nm == null ? null : file_nm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILE_MANAGE.STRE_NM
     *
     * @return the value of FILE_MANAGE.STRE_NM
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    public String getStre_nm() {
        return stre_nm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILE_MANAGE.STRE_NM
     *
     * @param stre_nm the value for FILE_MANAGE.STRE_NM
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    public void setStre_nm(String stre_nm) {
        this.stre_nm = stre_nm == null ? null : stre_nm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILE_MANAGE.DETAIL_STRE_COURS
     *
     * @return the value of FILE_MANAGE.DETAIL_STRE_COURS
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    public String getDetail_stre_cours() {
        return detail_stre_cours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILE_MANAGE.DETAIL_STRE_COURS
     *
     * @param detail_stre_cours the value for FILE_MANAGE.DETAIL_STRE_COURS
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    public void setDetail_stre_cours(String detail_stre_cours) {
        this.detail_stre_cours = detail_stre_cours == null ? null : detail_stre_cours.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILE_MANAGE.ROOT_STRE_COURS
     *
     * @return the value of FILE_MANAGE.ROOT_STRE_COURS
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    public String getRoot_stre_cours() {
        return root_stre_cours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILE_MANAGE.ROOT_STRE_COURS
     *
     * @param root_stre_cours the value for FILE_MANAGE.ROOT_STRE_COURS
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    public void setRoot_stre_cours(String root_stre_cours) {
        this.root_stre_cours = root_stre_cours == null ? null : root_stre_cours.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILE_MANAGE.FANCY_SIZE
     *
     * @return the value of FILE_MANAGE.FANCY_SIZE
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    public String getFancy_size() {
        return fancy_size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILE_MANAGE.FANCY_SIZE
     *
     * @param fancy_size the value for FILE_MANAGE.FANCY_SIZE
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    public void setFancy_size(String fancy_size) {
        this.fancy_size = fancy_size == null ? null : fancy_size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILE_MANAGE.REGISTER
     *
     * @return the value of FILE_MANAGE.REGISTER
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    public String getRegister() {
        return register;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILE_MANAGE.REGISTER
     *
     * @param register the value for FILE_MANAGE.REGISTER
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    public void setRegister(String register) {
        this.register = register == null ? null : register.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILE_MANAGE.TABLE_SE
     *
     * @return the value of FILE_MANAGE.TABLE_SE
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    public String getTableSe() {
        return tableSe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILE_MANAGE.TABLE_SE
     *
     * @param tableSe the value for FILE_MANAGE.TABLE_SE
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    public void setTableSe(String tableSe) {
        this.tableSe = tableSe == null ? null : tableSe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILE_MANAGE.REG_YN
     *
     * @return the value of FILE_MANAGE.REG_YN
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    public String getRegYn() {
        return regYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILE_MANAGE.REG_YN
     *
     * @param regYn the value for FILE_MANAGE.REG_YN
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    public void setRegYn(String regYn) {
        this.regYn = regYn == null ? null : regYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILE_MANAGE.REG_DE
     *
     * @return the value of FILE_MANAGE.REG_DE
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    public Date getRegDe() {
        return regDe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILE_MANAGE.REG_DE
     *
     * @param regDe the value for FILE_MANAGE.REG_DE
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    public void setRegDe(Date regDe) {
        this.regDe = regDe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILE_MANAGE.FILE_SIZE
     *
     * @return the value of FILE_MANAGE.FILE_SIZE
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    public String getFile_size() {
        return file_size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILE_MANAGE.FILE_SIZE
     *
     * @param file_size the value for FILE_MANAGE.FILE_SIZE
     *
     * @mbg.generated Sat Feb 10 13:55:57 KST 2018
     */
    public void setFile_size(String file_size) {
        this.file_size = file_size == null ? null : file_size.trim();
    }
}