package tk.tourwith.project.member.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MbListExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MB_LIST
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MB_LIST
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MB_LIST
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MB_LIST
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public MbListExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MB_LIST
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MB_LIST
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MB_LIST
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MB_LIST
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MB_LIST
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MB_LIST
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MB_LIST
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MB_LIST
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MB_LIST
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MB_LIST
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MB_LIST
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMb_noIsNull() {
            addCriterion("MB_NO is null");
            return (Criteria) this;
        }

        public Criteria andMb_noIsNotNull() {
            addCriterion("MB_NO is not null");
            return (Criteria) this;
        }

        public Criteria andMb_noEqualTo(String value) {
            addCriterion("MB_NO =", value, "mb_no");
            return (Criteria) this;
        }

        public Criteria andMb_noNotEqualTo(String value) {
            addCriterion("MB_NO <>", value, "mb_no");
            return (Criteria) this;
        }

        public Criteria andMb_noGreaterThan(String value) {
            addCriterion("MB_NO >", value, "mb_no");
            return (Criteria) this;
        }

        public Criteria andMb_noGreaterThanOrEqualTo(String value) {
            addCriterion("MB_NO >=", value, "mb_no");
            return (Criteria) this;
        }

        public Criteria andMb_noLessThan(String value) {
            addCriterion("MB_NO <", value, "mb_no");
            return (Criteria) this;
        }

        public Criteria andMb_noLessThanOrEqualTo(String value) {
            addCriterion("MB_NO <=", value, "mb_no");
            return (Criteria) this;
        }

        public Criteria andMb_noLike(String value) {
            addCriterion("MB_NO like", value, "mb_no");
            return (Criteria) this;
        }

        public Criteria andMb_noNotLike(String value) {
            addCriterion("MB_NO not like", value, "mb_no");
            return (Criteria) this;
        }

        public Criteria andMb_noIn(List<String> values) {
            addCriterion("MB_NO in", values, "mb_no");
            return (Criteria) this;
        }

        public Criteria andMb_noNotIn(List<String> values) {
            addCriterion("MB_NO not in", values, "mb_no");
            return (Criteria) this;
        }

        public Criteria andMb_noBetween(String value1, String value2) {
            addCriterion("MB_NO between", value1, value2, "mb_no");
            return (Criteria) this;
        }

        public Criteria andMb_noNotBetween(String value1, String value2) {
            addCriterion("MB_NO not between", value1, value2, "mb_no");
            return (Criteria) this;
        }

        public Criteria andNickIsNull() {
            addCriterion("NICK is null");
            return (Criteria) this;
        }

        public Criteria andNickIsNotNull() {
            addCriterion("NICK is not null");
            return (Criteria) this;
        }

        public Criteria andNickEqualTo(String value) {
            addCriterion("NICK =", value, "nick");
            return (Criteria) this;
        }

        public Criteria andNickNotEqualTo(String value) {
            addCriterion("NICK <>", value, "nick");
            return (Criteria) this;
        }

        public Criteria andNickGreaterThan(String value) {
            addCriterion("NICK >", value, "nick");
            return (Criteria) this;
        }

        public Criteria andNickGreaterThanOrEqualTo(String value) {
            addCriterion("NICK >=", value, "nick");
            return (Criteria) this;
        }

        public Criteria andNickLessThan(String value) {
            addCriterion("NICK <", value, "nick");
            return (Criteria) this;
        }

        public Criteria andNickLessThanOrEqualTo(String value) {
            addCriterion("NICK <=", value, "nick");
            return (Criteria) this;
        }

        public Criteria andNickLike(String value) {
            addCriterion("NICK like", value, "nick");
            return (Criteria) this;
        }

        public Criteria andNickNotLike(String value) {
            addCriterion("NICK not like", value, "nick");
            return (Criteria) this;
        }

        public Criteria andNickIn(List<String> values) {
            addCriterion("NICK in", values, "nick");
            return (Criteria) this;
        }

        public Criteria andNickNotIn(List<String> values) {
            addCriterion("NICK not in", values, "nick");
            return (Criteria) this;
        }

        public Criteria andNickBetween(String value1, String value2) {
            addCriterion("NICK between", value1, value2, "nick");
            return (Criteria) this;
        }

        public Criteria andNickNotBetween(String value1, String value2) {
            addCriterion("NICK not between", value1, value2, "nick");
            return (Criteria) this;
        }

        public Criteria andMb_gradIsNull() {
            addCriterion("MB_GRAD is null");
            return (Criteria) this;
        }

        public Criteria andMb_gradIsNotNull() {
            addCriterion("MB_GRAD is not null");
            return (Criteria) this;
        }

        public Criteria andMb_gradEqualTo(String value) {
            addCriterion("MB_GRAD =", value, "mb_grad");
            return (Criteria) this;
        }

        public Criteria andMb_gradNotEqualTo(String value) {
            addCriterion("MB_GRAD <>", value, "mb_grad");
            return (Criteria) this;
        }

        public Criteria andMb_gradGreaterThan(String value) {
            addCriterion("MB_GRAD >", value, "mb_grad");
            return (Criteria) this;
        }

        public Criteria andMb_gradGreaterThanOrEqualTo(String value) {
            addCriterion("MB_GRAD >=", value, "mb_grad");
            return (Criteria) this;
        }

        public Criteria andMb_gradLessThan(String value) {
            addCriterion("MB_GRAD <", value, "mb_grad");
            return (Criteria) this;
        }

        public Criteria andMb_gradLessThanOrEqualTo(String value) {
            addCriterion("MB_GRAD <=", value, "mb_grad");
            return (Criteria) this;
        }

        public Criteria andMb_gradLike(String value) {
            addCriterion("MB_GRAD like", value, "mb_grad");
            return (Criteria) this;
        }

        public Criteria andMb_gradNotLike(String value) {
            addCriterion("MB_GRAD not like", value, "mb_grad");
            return (Criteria) this;
        }

        public Criteria andMb_gradIn(List<String> values) {
            addCriterion("MB_GRAD in", values, "mb_grad");
            return (Criteria) this;
        }

        public Criteria andMb_gradNotIn(List<String> values) {
            addCriterion("MB_GRAD not in", values, "mb_grad");
            return (Criteria) this;
        }

        public Criteria andMb_gradBetween(String value1, String value2) {
            addCriterion("MB_GRAD between", value1, value2, "mb_grad");
            return (Criteria) this;
        }

        public Criteria andMb_gradNotBetween(String value1, String value2) {
            addCriterion("MB_GRAD not between", value1, value2, "mb_grad");
            return (Criteria) this;
        }

        public Criteria andFb_idIsNull() {
            addCriterion("FB_ID is null");
            return (Criteria) this;
        }

        public Criteria andFb_idIsNotNull() {
            addCriterion("FB_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFb_idEqualTo(String value) {
            addCriterion("FB_ID =", value, "fb_id");
            return (Criteria) this;
        }

        public Criteria andFb_idNotEqualTo(String value) {
            addCriterion("FB_ID <>", value, "fb_id");
            return (Criteria) this;
        }

        public Criteria andFb_idGreaterThan(String value) {
            addCriterion("FB_ID >", value, "fb_id");
            return (Criteria) this;
        }

        public Criteria andFb_idGreaterThanOrEqualTo(String value) {
            addCriterion("FB_ID >=", value, "fb_id");
            return (Criteria) this;
        }

        public Criteria andFb_idLessThan(String value) {
            addCriterion("FB_ID <", value, "fb_id");
            return (Criteria) this;
        }

        public Criteria andFb_idLessThanOrEqualTo(String value) {
            addCriterion("FB_ID <=", value, "fb_id");
            return (Criteria) this;
        }

        public Criteria andFb_idLike(String value) {
            addCriterion("FB_ID like", value, "fb_id");
            return (Criteria) this;
        }

        public Criteria andFb_idNotLike(String value) {
            addCriterion("FB_ID not like", value, "fb_id");
            return (Criteria) this;
        }

        public Criteria andFb_idIn(List<String> values) {
            addCriterion("FB_ID in", values, "fb_id");
            return (Criteria) this;
        }

        public Criteria andFb_idNotIn(List<String> values) {
            addCriterion("FB_ID not in", values, "fb_id");
            return (Criteria) this;
        }

        public Criteria andFb_idBetween(String value1, String value2) {
            addCriterion("FB_ID between", value1, value2, "fb_id");
            return (Criteria) this;
        }

        public Criteria andFb_idNotBetween(String value1, String value2) {
            addCriterion("FB_ID not between", value1, value2, "fb_id");
            return (Criteria) this;
        }

        public Criteria andFb_tknIsNull() {
            addCriterion("FB_TKN is null");
            return (Criteria) this;
        }

        public Criteria andFb_tknIsNotNull() {
            addCriterion("FB_TKN is not null");
            return (Criteria) this;
        }

        public Criteria andFb_tknEqualTo(String value) {
            addCriterion("FB_TKN =", value, "fb_tkn");
            return (Criteria) this;
        }

        public Criteria andFb_tknNotEqualTo(String value) {
            addCriterion("FB_TKN <>", value, "fb_tkn");
            return (Criteria) this;
        }

        public Criteria andFb_tknGreaterThan(String value) {
            addCriterion("FB_TKN >", value, "fb_tkn");
            return (Criteria) this;
        }

        public Criteria andFb_tknGreaterThanOrEqualTo(String value) {
            addCriterion("FB_TKN >=", value, "fb_tkn");
            return (Criteria) this;
        }

        public Criteria andFb_tknLessThan(String value) {
            addCriterion("FB_TKN <", value, "fb_tkn");
            return (Criteria) this;
        }

        public Criteria andFb_tknLessThanOrEqualTo(String value) {
            addCriterion("FB_TKN <=", value, "fb_tkn");
            return (Criteria) this;
        }

        public Criteria andFb_tknLike(String value) {
            addCriterion("FB_TKN like", value, "fb_tkn");
            return (Criteria) this;
        }

        public Criteria andFb_tknNotLike(String value) {
            addCriterion("FB_TKN not like", value, "fb_tkn");
            return (Criteria) this;
        }

        public Criteria andFb_tknIn(List<String> values) {
            addCriterion("FB_TKN in", values, "fb_tkn");
            return (Criteria) this;
        }

        public Criteria andFb_tknNotIn(List<String> values) {
            addCriterion("FB_TKN not in", values, "fb_tkn");
            return (Criteria) this;
        }

        public Criteria andFb_tknBetween(String value1, String value2) {
            addCriterion("FB_TKN between", value1, value2, "fb_tkn");
            return (Criteria) this;
        }

        public Criteria andFb_tknNotBetween(String value1, String value2) {
            addCriterion("FB_TKN not between", value1, value2, "fb_tkn");
            return (Criteria) this;
        }

        public Criteria andReg_deIsNull() {
            addCriterion("REG_DE is null");
            return (Criteria) this;
        }

        public Criteria andReg_deIsNotNull() {
            addCriterion("REG_DE is not null");
            return (Criteria) this;
        }

        public Criteria andReg_deEqualTo(Date value) {
            addCriterion("REG_DE =", value, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deNotEqualTo(Date value) {
            addCriterion("REG_DE <>", value, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deGreaterThan(Date value) {
            addCriterion("REG_DE >", value, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deGreaterThanOrEqualTo(Date value) {
            addCriterion("REG_DE >=", value, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deLessThan(Date value) {
            addCriterion("REG_DE <", value, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deLessThanOrEqualTo(Date value) {
            addCriterion("REG_DE <=", value, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deIn(List<Date> values) {
            addCriterion("REG_DE in", values, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deNotIn(List<Date> values) {
            addCriterion("REG_DE not in", values, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deBetween(Date value1, Date value2) {
            addCriterion("REG_DE between", value1, value2, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deNotBetween(Date value1, Date value2) {
            addCriterion("REG_DE not between", value1, value2, "reg_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deIsNull() {
            addCriterion("UPD_DE is null");
            return (Criteria) this;
        }

        public Criteria andUpd_deIsNotNull() {
            addCriterion("UPD_DE is not null");
            return (Criteria) this;
        }

        public Criteria andUpd_deEqualTo(Date value) {
            addCriterion("UPD_DE =", value, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deNotEqualTo(Date value) {
            addCriterion("UPD_DE <>", value, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deGreaterThan(Date value) {
            addCriterion("UPD_DE >", value, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deGreaterThanOrEqualTo(Date value) {
            addCriterion("UPD_DE >=", value, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deLessThan(Date value) {
            addCriterion("UPD_DE <", value, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deLessThanOrEqualTo(Date value) {
            addCriterion("UPD_DE <=", value, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deIn(List<Date> values) {
            addCriterion("UPD_DE in", values, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deNotIn(List<Date> values) {
            addCriterion("UPD_DE not in", values, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deBetween(Date value1, Date value2) {
            addCriterion("UPD_DE between", value1, value2, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deNotBetween(Date value1, Date value2) {
            addCriterion("UPD_DE not between", value1, value2, "upd_de");
            return (Criteria) this;
        }

        public Criteria andDel_ynIsNull() {
            addCriterion("DEL_YN is null");
            return (Criteria) this;
        }

        public Criteria andDel_ynIsNotNull() {
            addCriterion("DEL_YN is not null");
            return (Criteria) this;
        }

        public Criteria andDel_ynEqualTo(String value) {
            addCriterion("DEL_YN =", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynNotEqualTo(String value) {
            addCriterion("DEL_YN <>", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynGreaterThan(String value) {
            addCriterion("DEL_YN >", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynGreaterThanOrEqualTo(String value) {
            addCriterion("DEL_YN >=", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynLessThan(String value) {
            addCriterion("DEL_YN <", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynLessThanOrEqualTo(String value) {
            addCriterion("DEL_YN <=", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynLike(String value) {
            addCriterion("DEL_YN like", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynNotLike(String value) {
            addCriterion("DEL_YN not like", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynIn(List<String> values) {
            addCriterion("DEL_YN in", values, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynNotIn(List<String> values) {
            addCriterion("DEL_YN not in", values, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynBetween(String value1, String value2) {
            addCriterion("DEL_YN between", value1, value2, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynNotBetween(String value1, String value2) {
            addCriterion("DEL_YN not between", value1, value2, "del_yn");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("GENDER is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("GENDER is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(String value) {
            addCriterion("GENDER =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(String value) {
            addCriterion("GENDER <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(String value) {
            addCriterion("GENDER >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(String value) {
            addCriterion("GENDER >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(String value) {
            addCriterion("GENDER <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(String value) {
            addCriterion("GENDER <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLike(String value) {
            addCriterion("GENDER like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotLike(String value) {
            addCriterion("GENDER not like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<String> values) {
            addCriterion("GENDER in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<String> values) {
            addCriterion("GENDER not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(String value1, String value2) {
            addCriterion("GENDER between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(String value1, String value2) {
            addCriterion("GENDER not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("AGE is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("AGE is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(Integer value) {
            addCriterion("AGE =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(Integer value) {
            addCriterion("AGE <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(Integer value) {
            addCriterion("AGE >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("AGE >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(Integer value) {
            addCriterion("AGE <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(Integer value) {
            addCriterion("AGE <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<Integer> values) {
            addCriterion("AGE in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<Integer> values) {
            addCriterion("AGE not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(Integer value1, Integer value2) {
            addCriterion("AGE between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("AGE not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andTour_cntIsNull() {
            addCriterion("TOUR_CNT is null");
            return (Criteria) this;
        }

        public Criteria andTour_cntIsNotNull() {
            addCriterion("TOUR_CNT is not null");
            return (Criteria) this;
        }

        public Criteria andTour_cntEqualTo(Integer value) {
            addCriterion("TOUR_CNT =", value, "tour_cnt");
            return (Criteria) this;
        }

        public Criteria andTour_cntNotEqualTo(Integer value) {
            addCriterion("TOUR_CNT <>", value, "tour_cnt");
            return (Criteria) this;
        }

        public Criteria andTour_cntGreaterThan(Integer value) {
            addCriterion("TOUR_CNT >", value, "tour_cnt");
            return (Criteria) this;
        }

        public Criteria andTour_cntGreaterThanOrEqualTo(Integer value) {
            addCriterion("TOUR_CNT >=", value, "tour_cnt");
            return (Criteria) this;
        }

        public Criteria andTour_cntLessThan(Integer value) {
            addCriterion("TOUR_CNT <", value, "tour_cnt");
            return (Criteria) this;
        }

        public Criteria andTour_cntLessThanOrEqualTo(Integer value) {
            addCriterion("TOUR_CNT <=", value, "tour_cnt");
            return (Criteria) this;
        }

        public Criteria andTour_cntIn(List<Integer> values) {
            addCriterion("TOUR_CNT in", values, "tour_cnt");
            return (Criteria) this;
        }

        public Criteria andTour_cntNotIn(List<Integer> values) {
            addCriterion("TOUR_CNT not in", values, "tour_cnt");
            return (Criteria) this;
        }

        public Criteria andTour_cntBetween(Integer value1, Integer value2) {
            addCriterion("TOUR_CNT between", value1, value2, "tour_cnt");
            return (Criteria) this;
        }

        public Criteria andTour_cntNotBetween(Integer value1, Integer value2) {
            addCriterion("TOUR_CNT not between", value1, value2, "tour_cnt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MB_LIST
     *
     * @mbg.generated do_not_delete_during_merge Mon Feb 12 09:25:53 KST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MB_LIST
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}