package tk.tourwith.project.member.model;

import java.util.Date;

public class MbList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MB_LIST.MB_NO
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    private String mb_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MB_LIST.NICK
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    private String nick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MB_LIST.MB_GRAD
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    private String mb_grad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MB_LIST.FB_ID
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    private String fb_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MB_LIST.FB_TKN
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    private String fb_tkn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MB_LIST.REG_DE
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    private Date reg_de;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MB_LIST.UPD_DE
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    private Date upd_de;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MB_LIST.DEL_YN
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    private String del_yn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MB_LIST.GENDER
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MB_LIST.AGE
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MB_LIST.TOUR_CNT
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    private Integer tour_cnt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MB_LIST.MB_NO
     *
     * @return the value of MB_LIST.MB_NO
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public String getMb_no() {
        return mb_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MB_LIST.MB_NO
     *
     * @param mb_no the value for MB_LIST.MB_NO
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public void setMb_no(String mb_no) {
        this.mb_no = mb_no == null ? null : mb_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MB_LIST.NICK
     *
     * @return the value of MB_LIST.NICK
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public String getNick() {
        return nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MB_LIST.NICK
     *
     * @param nick the value for MB_LIST.NICK
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public void setNick(String nick) {
        this.nick = nick == null ? null : nick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MB_LIST.MB_GRAD
     *
     * @return the value of MB_LIST.MB_GRAD
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public String getMb_grad() {
        return mb_grad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MB_LIST.MB_GRAD
     *
     * @param mb_grad the value for MB_LIST.MB_GRAD
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public void setMb_grad(String mb_grad) {
        this.mb_grad = mb_grad == null ? null : mb_grad.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MB_LIST.FB_ID
     *
     * @return the value of MB_LIST.FB_ID
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public String getFb_id() {
        return fb_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MB_LIST.FB_ID
     *
     * @param fb_id the value for MB_LIST.FB_ID
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public void setFb_id(String fb_id) {
        this.fb_id = fb_id == null ? null : fb_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MB_LIST.FB_TKN
     *
     * @return the value of MB_LIST.FB_TKN
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public String getFb_tkn() {
        return fb_tkn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MB_LIST.FB_TKN
     *
     * @param fb_tkn the value for MB_LIST.FB_TKN
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public void setFb_tkn(String fb_tkn) {
        this.fb_tkn = fb_tkn == null ? null : fb_tkn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MB_LIST.REG_DE
     *
     * @return the value of MB_LIST.REG_DE
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public Date getReg_de() {
        return reg_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MB_LIST.REG_DE
     *
     * @param reg_de the value for MB_LIST.REG_DE
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public void setReg_de(Date reg_de) {
        this.reg_de = reg_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MB_LIST.UPD_DE
     *
     * @return the value of MB_LIST.UPD_DE
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public Date getUpd_de() {
        return upd_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MB_LIST.UPD_DE
     *
     * @param upd_de the value for MB_LIST.UPD_DE
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public void setUpd_de(Date upd_de) {
        this.upd_de = upd_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MB_LIST.DEL_YN
     *
     * @return the value of MB_LIST.DEL_YN
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public String getDel_yn() {
        return del_yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MB_LIST.DEL_YN
     *
     * @param del_yn the value for MB_LIST.DEL_YN
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public void setDel_yn(String del_yn) {
        this.del_yn = del_yn == null ? null : del_yn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MB_LIST.GENDER
     *
     * @return the value of MB_LIST.GENDER
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MB_LIST.GENDER
     *
     * @param gender the value for MB_LIST.GENDER
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MB_LIST.AGE
     *
     * @return the value of MB_LIST.AGE
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MB_LIST.AGE
     *
     * @param age the value for MB_LIST.AGE
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MB_LIST.TOUR_CNT
     *
     * @return the value of MB_LIST.TOUR_CNT
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public Integer getTour_cnt() {
        return tour_cnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MB_LIST.TOUR_CNT
     *
     * @param tour_cnt the value for MB_LIST.TOUR_CNT
     *
     * @mbg.generated Mon Feb 12 09:25:53 KST 2018
     */
    public void setTour_cnt(Integer tour_cnt) {
        this.tour_cnt = tour_cnt;
    }
}