package tk.tourwith.project.util.trplc.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TrplcInfoManageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TRPLC_INFO_MANAGE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TRPLC_INFO_MANAGE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TRPLC_INFO_MANAGE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRPLC_INFO_MANAGE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    public TrplcInfoManageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRPLC_INFO_MANAGE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRPLC_INFO_MANAGE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRPLC_INFO_MANAGE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRPLC_INFO_MANAGE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRPLC_INFO_MANAGE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRPLC_INFO_MANAGE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRPLC_INFO_MANAGE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRPLC_INFO_MANAGE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRPLC_INFO_MANAGE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRPLC_INFO_MANAGE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TRPLC_INFO_MANAGE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTrplc_noIsNull() {
            addCriterion("TRPLC_NO is null");
            return (Criteria) this;
        }

        public Criteria andTrplc_noIsNotNull() {
            addCriterion("TRPLC_NO is not null");
            return (Criteria) this;
        }

        public Criteria andTrplc_noEqualTo(String value) {
            addCriterion("TRPLC_NO =", value, "trplc_no");
            return (Criteria) this;
        }

        public Criteria andTrplc_noNotEqualTo(String value) {
            addCriterion("TRPLC_NO <>", value, "trplc_no");
            return (Criteria) this;
        }

        public Criteria andTrplc_noGreaterThan(String value) {
            addCriterion("TRPLC_NO >", value, "trplc_no");
            return (Criteria) this;
        }

        public Criteria andTrplc_noGreaterThanOrEqualTo(String value) {
            addCriterion("TRPLC_NO >=", value, "trplc_no");
            return (Criteria) this;
        }

        public Criteria andTrplc_noLessThan(String value) {
            addCriterion("TRPLC_NO <", value, "trplc_no");
            return (Criteria) this;
        }

        public Criteria andTrplc_noLessThanOrEqualTo(String value) {
            addCriterion("TRPLC_NO <=", value, "trplc_no");
            return (Criteria) this;
        }

        public Criteria andTrplc_noLike(String value) {
            addCriterion("TRPLC_NO like", value, "trplc_no");
            return (Criteria) this;
        }

        public Criteria andTrplc_noNotLike(String value) {
            addCriterion("TRPLC_NO not like", value, "trplc_no");
            return (Criteria) this;
        }

        public Criteria andTrplc_noIn(List<String> values) {
            addCriterion("TRPLC_NO in", values, "trplc_no");
            return (Criteria) this;
        }

        public Criteria andTrplc_noNotIn(List<String> values) {
            addCriterion("TRPLC_NO not in", values, "trplc_no");
            return (Criteria) this;
        }

        public Criteria andTrplc_noBetween(String value1, String value2) {
            addCriterion("TRPLC_NO between", value1, value2, "trplc_no");
            return (Criteria) this;
        }

        public Criteria andTrplc_noNotBetween(String value1, String value2) {
            addCriterion("TRPLC_NO not between", value1, value2, "trplc_no");
            return (Criteria) this;
        }

        public Criteria andTrplc_ctgryIsNull() {
            addCriterion("TRPLC_CTGRY is null");
            return (Criteria) this;
        }

        public Criteria andTrplc_ctgryIsNotNull() {
            addCriterion("TRPLC_CTGRY is not null");
            return (Criteria) this;
        }

        public Criteria andTrplc_ctgryEqualTo(String value) {
            addCriterion("TRPLC_CTGRY =", value, "trplc_ctgry");
            return (Criteria) this;
        }

        public Criteria andTrplc_ctgryNotEqualTo(String value) {
            addCriterion("TRPLC_CTGRY <>", value, "trplc_ctgry");
            return (Criteria) this;
        }

        public Criteria andTrplc_ctgryGreaterThan(String value) {
            addCriterion("TRPLC_CTGRY >", value, "trplc_ctgry");
            return (Criteria) this;
        }

        public Criteria andTrplc_ctgryGreaterThanOrEqualTo(String value) {
            addCriterion("TRPLC_CTGRY >=", value, "trplc_ctgry");
            return (Criteria) this;
        }

        public Criteria andTrplc_ctgryLessThan(String value) {
            addCriterion("TRPLC_CTGRY <", value, "trplc_ctgry");
            return (Criteria) this;
        }

        public Criteria andTrplc_ctgryLessThanOrEqualTo(String value) {
            addCriterion("TRPLC_CTGRY <=", value, "trplc_ctgry");
            return (Criteria) this;
        }

        public Criteria andTrplc_ctgryLike(String value) {
            addCriterion("TRPLC_CTGRY like", value, "trplc_ctgry");
            return (Criteria) this;
        }

        public Criteria andTrplc_ctgryNotLike(String value) {
            addCriterion("TRPLC_CTGRY not like", value, "trplc_ctgry");
            return (Criteria) this;
        }

        public Criteria andTrplc_ctgryIn(List<String> values) {
            addCriterion("TRPLC_CTGRY in", values, "trplc_ctgry");
            return (Criteria) this;
        }

        public Criteria andTrplc_ctgryNotIn(List<String> values) {
            addCriterion("TRPLC_CTGRY not in", values, "trplc_ctgry");
            return (Criteria) this;
        }

        public Criteria andTrplc_ctgryBetween(String value1, String value2) {
            addCriterion("TRPLC_CTGRY between", value1, value2, "trplc_ctgry");
            return (Criteria) this;
        }

        public Criteria andTrplc_ctgryNotBetween(String value1, String value2) {
            addCriterion("TRPLC_CTGRY not between", value1, value2, "trplc_ctgry");
            return (Criteria) this;
        }

        public Criteria andReg_deIsNull() {
            addCriterion("REG_DE is null");
            return (Criteria) this;
        }

        public Criteria andReg_deIsNotNull() {
            addCriterion("REG_DE is not null");
            return (Criteria) this;
        }

        public Criteria andReg_deEqualTo(Date value) {
            addCriterion("REG_DE =", value, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deNotEqualTo(Date value) {
            addCriterion("REG_DE <>", value, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deGreaterThan(Date value) {
            addCriterion("REG_DE >", value, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deGreaterThanOrEqualTo(Date value) {
            addCriterion("REG_DE >=", value, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deLessThan(Date value) {
            addCriterion("REG_DE <", value, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deLessThanOrEqualTo(Date value) {
            addCriterion("REG_DE <=", value, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deIn(List<Date> values) {
            addCriterion("REG_DE in", values, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deNotIn(List<Date> values) {
            addCriterion("REG_DE not in", values, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deBetween(Date value1, Date value2) {
            addCriterion("REG_DE between", value1, value2, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deNotBetween(Date value1, Date value2) {
            addCriterion("REG_DE not between", value1, value2, "reg_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deIsNull() {
            addCriterion("UPD_DE is null");
            return (Criteria) this;
        }

        public Criteria andUpd_deIsNotNull() {
            addCriterion("UPD_DE is not null");
            return (Criteria) this;
        }

        public Criteria andUpd_deEqualTo(Date value) {
            addCriterion("UPD_DE =", value, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deNotEqualTo(Date value) {
            addCriterion("UPD_DE <>", value, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deGreaterThan(Date value) {
            addCriterion("UPD_DE >", value, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deGreaterThanOrEqualTo(Date value) {
            addCriterion("UPD_DE >=", value, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deLessThan(Date value) {
            addCriterion("UPD_DE <", value, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deLessThanOrEqualTo(Date value) {
            addCriterion("UPD_DE <=", value, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deIn(List<Date> values) {
            addCriterion("UPD_DE in", values, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deNotIn(List<Date> values) {
            addCriterion("UPD_DE not in", values, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deBetween(Date value1, Date value2) {
            addCriterion("UPD_DE between", value1, value2, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deNotBetween(Date value1, Date value2) {
            addCriterion("UPD_DE not between", value1, value2, "upd_de");
            return (Criteria) this;
        }

        public Criteria andTrplc_detail_ctgryIsNull() {
            addCriterion("TRPLC_DETAIL_CTGRY is null");
            return (Criteria) this;
        }

        public Criteria andTrplc_detail_ctgryIsNotNull() {
            addCriterion("TRPLC_DETAIL_CTGRY is not null");
            return (Criteria) this;
        }

        public Criteria andTrplc_detail_ctgryEqualTo(String value) {
            addCriterion("TRPLC_DETAIL_CTGRY =", value, "trplc_detail_ctgry");
            return (Criteria) this;
        }

        public Criteria andTrplc_detail_ctgryNotEqualTo(String value) {
            addCriterion("TRPLC_DETAIL_CTGRY <>", value, "trplc_detail_ctgry");
            return (Criteria) this;
        }

        public Criteria andTrplc_detail_ctgryGreaterThan(String value) {
            addCriterion("TRPLC_DETAIL_CTGRY >", value, "trplc_detail_ctgry");
            return (Criteria) this;
        }

        public Criteria andTrplc_detail_ctgryGreaterThanOrEqualTo(String value) {
            addCriterion("TRPLC_DETAIL_CTGRY >=", value, "trplc_detail_ctgry");
            return (Criteria) this;
        }

        public Criteria andTrplc_detail_ctgryLessThan(String value) {
            addCriterion("TRPLC_DETAIL_CTGRY <", value, "trplc_detail_ctgry");
            return (Criteria) this;
        }

        public Criteria andTrplc_detail_ctgryLessThanOrEqualTo(String value) {
            addCriterion("TRPLC_DETAIL_CTGRY <=", value, "trplc_detail_ctgry");
            return (Criteria) this;
        }

        public Criteria andTrplc_detail_ctgryLike(String value) {
            addCriterion("TRPLC_DETAIL_CTGRY like", value, "trplc_detail_ctgry");
            return (Criteria) this;
        }

        public Criteria andTrplc_detail_ctgryNotLike(String value) {
            addCriterion("TRPLC_DETAIL_CTGRY not like", value, "trplc_detail_ctgry");
            return (Criteria) this;
        }

        public Criteria andTrplc_detail_ctgryIn(List<String> values) {
            addCriterion("TRPLC_DETAIL_CTGRY in", values, "trplc_detail_ctgry");
            return (Criteria) this;
        }

        public Criteria andTrplc_detail_ctgryNotIn(List<String> values) {
            addCriterion("TRPLC_DETAIL_CTGRY not in", values, "trplc_detail_ctgry");
            return (Criteria) this;
        }

        public Criteria andTrplc_detail_ctgryBetween(String value1, String value2) {
            addCriterion("TRPLC_DETAIL_CTGRY between", value1, value2, "trplc_detail_ctgry");
            return (Criteria) this;
        }

        public Criteria andTrplc_detail_ctgryNotBetween(String value1, String value2) {
            addCriterion("TRPLC_DETAIL_CTGRY not between", value1, value2, "trplc_detail_ctgry");
            return (Criteria) this;
        }

        public Criteria andLatiIsNull() {
            addCriterion("LATI is null");
            return (Criteria) this;
        }

        public Criteria andLatiIsNotNull() {
            addCriterion("LATI is not null");
            return (Criteria) this;
        }

        public Criteria andLatiEqualTo(Float value) {
            addCriterion("LATI =", value, "lati");
            return (Criteria) this;
        }

        public Criteria andLatiNotEqualTo(Float value) {
            addCriterion("LATI <>", value, "lati");
            return (Criteria) this;
        }

        public Criteria andLatiGreaterThan(Float value) {
            addCriterion("LATI >", value, "lati");
            return (Criteria) this;
        }

        public Criteria andLatiGreaterThanOrEqualTo(Float value) {
            addCriterion("LATI >=", value, "lati");
            return (Criteria) this;
        }

        public Criteria andLatiLessThan(Float value) {
            addCriterion("LATI <", value, "lati");
            return (Criteria) this;
        }

        public Criteria andLatiLessThanOrEqualTo(Float value) {
            addCriterion("LATI <=", value, "lati");
            return (Criteria) this;
        }

        public Criteria andLatiIn(List<Float> values) {
            addCriterion("LATI in", values, "lati");
            return (Criteria) this;
        }

        public Criteria andLatiNotIn(List<Float> values) {
            addCriterion("LATI not in", values, "lati");
            return (Criteria) this;
        }

        public Criteria andLatiBetween(Float value1, Float value2) {
            addCriterion("LATI between", value1, value2, "lati");
            return (Criteria) this;
        }

        public Criteria andLatiNotBetween(Float value1, Float value2) {
            addCriterion("LATI not between", value1, value2, "lati");
            return (Criteria) this;
        }

        public Criteria andLongiIsNull() {
            addCriterion("LONGI is null");
            return (Criteria) this;
        }

        public Criteria andLongiIsNotNull() {
            addCriterion("LONGI is not null");
            return (Criteria) this;
        }

        public Criteria andLongiEqualTo(Float value) {
            addCriterion("LONGI =", value, "longi");
            return (Criteria) this;
        }

        public Criteria andLongiNotEqualTo(Float value) {
            addCriterion("LONGI <>", value, "longi");
            return (Criteria) this;
        }

        public Criteria andLongiGreaterThan(Float value) {
            addCriterion("LONGI >", value, "longi");
            return (Criteria) this;
        }

        public Criteria andLongiGreaterThanOrEqualTo(Float value) {
            addCriterion("LONGI >=", value, "longi");
            return (Criteria) this;
        }

        public Criteria andLongiLessThan(Float value) {
            addCriterion("LONGI <", value, "longi");
            return (Criteria) this;
        }

        public Criteria andLongiLessThanOrEqualTo(Float value) {
            addCriterion("LONGI <=", value, "longi");
            return (Criteria) this;
        }

        public Criteria andLongiIn(List<Float> values) {
            addCriterion("LONGI in", values, "longi");
            return (Criteria) this;
        }

        public Criteria andLongiNotIn(List<Float> values) {
            addCriterion("LONGI not in", values, "longi");
            return (Criteria) this;
        }

        public Criteria andLongiBetween(Float value1, Float value2) {
            addCriterion("LONGI between", value1, value2, "longi");
            return (Criteria) this;
        }

        public Criteria andLongiNotBetween(Float value1, Float value2) {
            addCriterion("LONGI not between", value1, value2, "longi");
            return (Criteria) this;
        }

        public Criteria andWrterIsNull() {
            addCriterion("WRTER is null");
            return (Criteria) this;
        }

        public Criteria andWrterIsNotNull() {
            addCriterion("WRTER is not null");
            return (Criteria) this;
        }

        public Criteria andWrterEqualTo(String value) {
            addCriterion("WRTER =", value, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterNotEqualTo(String value) {
            addCriterion("WRTER <>", value, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterGreaterThan(String value) {
            addCriterion("WRTER >", value, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterGreaterThanOrEqualTo(String value) {
            addCriterion("WRTER >=", value, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterLessThan(String value) {
            addCriterion("WRTER <", value, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterLessThanOrEqualTo(String value) {
            addCriterion("WRTER <=", value, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterLike(String value) {
            addCriterion("WRTER like", value, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterNotLike(String value) {
            addCriterion("WRTER not like", value, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterIn(List<String> values) {
            addCriterion("WRTER in", values, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterNotIn(List<String> values) {
            addCriterion("WRTER not in", values, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterBetween(String value1, String value2) {
            addCriterion("WRTER between", value1, value2, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterNotBetween(String value1, String value2) {
            addCriterion("WRTER not between", value1, value2, "wrter");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TRPLC_INFO_MANAGE
     *
     * @mbg.generated do_not_delete_during_merge Fri Feb 09 12:28:44 KST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TRPLC_INFO_MANAGE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}