package tk.tourwith.project.util.trplc.model;

import java.util.Date;

public class TrplcInfoManage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRPLC_INFO_MANAGE.TRPLC_NO
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    private String trplc_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRPLC_INFO_MANAGE.TRPLC_CTGRY
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    private String trplc_ctgry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRPLC_INFO_MANAGE.REG_DE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    private Date reg_de;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRPLC_INFO_MANAGE.UPD_DE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    private Date upd_de;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRPLC_INFO_MANAGE.TRPLC_DETAIL_CTGRY
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    private String trplc_detail_ctgry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRPLC_INFO_MANAGE.LATI
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    private Float lati;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRPLC_INFO_MANAGE.LONGI
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    private Float longi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TRPLC_INFO_MANAGE.WRTER
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    private String wrter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRPLC_INFO_MANAGE.TRPLC_NO
     *
     * @return the value of TRPLC_INFO_MANAGE.TRPLC_NO
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    public String getTrplc_no() {
        return trplc_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRPLC_INFO_MANAGE.TRPLC_NO
     *
     * @param trplc_no the value for TRPLC_INFO_MANAGE.TRPLC_NO
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    public void setTrplc_no(String trplc_no) {
        this.trplc_no = trplc_no == null ? null : trplc_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRPLC_INFO_MANAGE.TRPLC_CTGRY
     *
     * @return the value of TRPLC_INFO_MANAGE.TRPLC_CTGRY
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    public String getTrplc_ctgry() {
        return trplc_ctgry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRPLC_INFO_MANAGE.TRPLC_CTGRY
     *
     * @param trplc_ctgry the value for TRPLC_INFO_MANAGE.TRPLC_CTGRY
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    public void setTrplc_ctgry(String trplc_ctgry) {
        this.trplc_ctgry = trplc_ctgry == null ? null : trplc_ctgry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRPLC_INFO_MANAGE.REG_DE
     *
     * @return the value of TRPLC_INFO_MANAGE.REG_DE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    public Date getReg_de() {
        return reg_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRPLC_INFO_MANAGE.REG_DE
     *
     * @param reg_de the value for TRPLC_INFO_MANAGE.REG_DE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    public void setReg_de(Date reg_de) {
        this.reg_de = reg_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRPLC_INFO_MANAGE.UPD_DE
     *
     * @return the value of TRPLC_INFO_MANAGE.UPD_DE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    public Date getUpd_de() {
        return upd_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRPLC_INFO_MANAGE.UPD_DE
     *
     * @param upd_de the value for TRPLC_INFO_MANAGE.UPD_DE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    public void setUpd_de(Date upd_de) {
        this.upd_de = upd_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRPLC_INFO_MANAGE.TRPLC_DETAIL_CTGRY
     *
     * @return the value of TRPLC_INFO_MANAGE.TRPLC_DETAIL_CTGRY
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    public String getTrplc_detail_ctgry() {
        return trplc_detail_ctgry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRPLC_INFO_MANAGE.TRPLC_DETAIL_CTGRY
     *
     * @param trplc_detail_ctgry the value for TRPLC_INFO_MANAGE.TRPLC_DETAIL_CTGRY
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    public void setTrplc_detail_ctgry(String trplc_detail_ctgry) {
        this.trplc_detail_ctgry = trplc_detail_ctgry == null ? null : trplc_detail_ctgry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRPLC_INFO_MANAGE.LATI
     *
     * @return the value of TRPLC_INFO_MANAGE.LATI
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    public Float getLati() {
        return lati;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRPLC_INFO_MANAGE.LATI
     *
     * @param lati the value for TRPLC_INFO_MANAGE.LATI
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    public void setLati(Float lati) {
        this.lati = lati;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRPLC_INFO_MANAGE.LONGI
     *
     * @return the value of TRPLC_INFO_MANAGE.LONGI
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    public Float getLongi() {
        return longi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRPLC_INFO_MANAGE.LONGI
     *
     * @param longi the value for TRPLC_INFO_MANAGE.LONGI
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    public void setLongi(Float longi) {
        this.longi = longi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TRPLC_INFO_MANAGE.WRTER
     *
     * @return the value of TRPLC_INFO_MANAGE.WRTER
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    public String getWrter() {
        return wrter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TRPLC_INFO_MANAGE.WRTER
     *
     * @param wrter the value for TRPLC_INFO_MANAGE.WRTER
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    public void setWrter(String wrter) {
        this.wrter = wrter == null ? null : wrter.trim();
    }
}