package tk.tourwith.project.bbs.notice.model;

import java.util.Date;

public class CrNoticeList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_NOTICE_LIST.SJ
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    private String sj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_NOTICE_LIST.HITCNT
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    private Integer hitcnt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_NOTICE_LIST.REG_DE
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    private Date reg_de;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_NOTICE_LIST.UPD_DE
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    private Date upd_de;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_NOTICE_LIST.DEL_YN
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    private String del_yn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_NOTICE_LIST.CR_NO
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    private String cr_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_NOTICE_LIST.WRTER
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    private String wrter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_NOTICE_LIST.NOTICE_NO
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    private String notice_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_NOTICE_LIST.UPDUSR
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    private String updusr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_NOTICE_LIST.CON
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    private String con;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_NOTICE_LIST.SJ
     *
     * @return the value of CR_NOTICE_LIST.SJ
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public String getSj() {
        return sj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_NOTICE_LIST.SJ
     *
     * @param sj the value for CR_NOTICE_LIST.SJ
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public void setSj(String sj) {
        this.sj = sj == null ? null : sj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_NOTICE_LIST.HITCNT
     *
     * @return the value of CR_NOTICE_LIST.HITCNT
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public Integer getHitcnt() {
        return hitcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_NOTICE_LIST.HITCNT
     *
     * @param hitcnt the value for CR_NOTICE_LIST.HITCNT
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public void setHitcnt(Integer hitcnt) {
        this.hitcnt = hitcnt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_NOTICE_LIST.REG_DE
     *
     * @return the value of CR_NOTICE_LIST.REG_DE
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public Date getReg_de() {
        return reg_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_NOTICE_LIST.REG_DE
     *
     * @param reg_de the value for CR_NOTICE_LIST.REG_DE
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public void setReg_de(Date reg_de) {
        this.reg_de = reg_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_NOTICE_LIST.UPD_DE
     *
     * @return the value of CR_NOTICE_LIST.UPD_DE
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public Date getUpd_de() {
        return upd_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_NOTICE_LIST.UPD_DE
     *
     * @param upd_de the value for CR_NOTICE_LIST.UPD_DE
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public void setUpd_de(Date upd_de) {
        this.upd_de = upd_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_NOTICE_LIST.DEL_YN
     *
     * @return the value of CR_NOTICE_LIST.DEL_YN
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public String getDel_yn() {
        return del_yn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_NOTICE_LIST.DEL_YN
     *
     * @param del_yn the value for CR_NOTICE_LIST.DEL_YN
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public void setDel_yn(String del_yn) {
        this.del_yn = del_yn == null ? null : del_yn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_NOTICE_LIST.CR_NO
     *
     * @return the value of CR_NOTICE_LIST.CR_NO
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public String getCr_no() {
        return cr_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_NOTICE_LIST.CR_NO
     *
     * @param cr_no the value for CR_NOTICE_LIST.CR_NO
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public void setCr_no(String cr_no) {
        this.cr_no = cr_no == null ? null : cr_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_NOTICE_LIST.WRTER
     *
     * @return the value of CR_NOTICE_LIST.WRTER
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public String getWrter() {
        return wrter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_NOTICE_LIST.WRTER
     *
     * @param wrter the value for CR_NOTICE_LIST.WRTER
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public void setWrter(String wrter) {
        this.wrter = wrter == null ? null : wrter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_NOTICE_LIST.NOTICE_NO
     *
     * @return the value of CR_NOTICE_LIST.NOTICE_NO
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public String getNotice_no() {
        return notice_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_NOTICE_LIST.NOTICE_NO
     *
     * @param notice_no the value for CR_NOTICE_LIST.NOTICE_NO
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public void setNotice_no(String notice_no) {
        this.notice_no = notice_no == null ? null : notice_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_NOTICE_LIST.UPDUSR
     *
     * @return the value of CR_NOTICE_LIST.UPDUSR
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public String getUpdusr() {
        return updusr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_NOTICE_LIST.UPDUSR
     *
     * @param updusr the value for CR_NOTICE_LIST.UPDUSR
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public void setUpdusr(String updusr) {
        this.updusr = updusr == null ? null : updusr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_NOTICE_LIST.CON
     *
     * @return the value of CR_NOTICE_LIST.CON
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public String getCon() {
        return con;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_NOTICE_LIST.CON
     *
     * @param con the value for CR_NOTICE_LIST.CON
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public void setCon(String con) {
        this.con = con == null ? null : con.trim();
    }
}