package tk.tourwith.project.bbs.notice.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CrNoticeListExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CR_NOTICE_LIST
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CR_NOTICE_LIST
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CR_NOTICE_LIST
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_NOTICE_LIST
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public CrNoticeListExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_NOTICE_LIST
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_NOTICE_LIST
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_NOTICE_LIST
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_NOTICE_LIST
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_NOTICE_LIST
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_NOTICE_LIST
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_NOTICE_LIST
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_NOTICE_LIST
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_NOTICE_LIST
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_NOTICE_LIST
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CR_NOTICE_LIST
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSjIsNull() {
            addCriterion("SJ is null");
            return (Criteria) this;
        }

        public Criteria andSjIsNotNull() {
            addCriterion("SJ is not null");
            return (Criteria) this;
        }

        public Criteria andSjEqualTo(String value) {
            addCriterion("SJ =", value, "sj");
            return (Criteria) this;
        }

        public Criteria andSjNotEqualTo(String value) {
            addCriterion("SJ <>", value, "sj");
            return (Criteria) this;
        }

        public Criteria andSjGreaterThan(String value) {
            addCriterion("SJ >", value, "sj");
            return (Criteria) this;
        }

        public Criteria andSjGreaterThanOrEqualTo(String value) {
            addCriterion("SJ >=", value, "sj");
            return (Criteria) this;
        }

        public Criteria andSjLessThan(String value) {
            addCriterion("SJ <", value, "sj");
            return (Criteria) this;
        }

        public Criteria andSjLessThanOrEqualTo(String value) {
            addCriterion("SJ <=", value, "sj");
            return (Criteria) this;
        }

        public Criteria andSjLike(String value) {
            addCriterion("SJ like", value, "sj");
            return (Criteria) this;
        }

        public Criteria andSjNotLike(String value) {
            addCriterion("SJ not like", value, "sj");
            return (Criteria) this;
        }

        public Criteria andSjIn(List<String> values) {
            addCriterion("SJ in", values, "sj");
            return (Criteria) this;
        }

        public Criteria andSjNotIn(List<String> values) {
            addCriterion("SJ not in", values, "sj");
            return (Criteria) this;
        }

        public Criteria andSjBetween(String value1, String value2) {
            addCriterion("SJ between", value1, value2, "sj");
            return (Criteria) this;
        }

        public Criteria andSjNotBetween(String value1, String value2) {
            addCriterion("SJ not between", value1, value2, "sj");
            return (Criteria) this;
        }

        public Criteria andHitcntIsNull() {
            addCriterion("HITCNT is null");
            return (Criteria) this;
        }

        public Criteria andHitcntIsNotNull() {
            addCriterion("HITCNT is not null");
            return (Criteria) this;
        }

        public Criteria andHitcntEqualTo(Integer value) {
            addCriterion("HITCNT =", value, "hitcnt");
            return (Criteria) this;
        }

        public Criteria andHitcntNotEqualTo(Integer value) {
            addCriterion("HITCNT <>", value, "hitcnt");
            return (Criteria) this;
        }

        public Criteria andHitcntGreaterThan(Integer value) {
            addCriterion("HITCNT >", value, "hitcnt");
            return (Criteria) this;
        }

        public Criteria andHitcntGreaterThanOrEqualTo(Integer value) {
            addCriterion("HITCNT >=", value, "hitcnt");
            return (Criteria) this;
        }

        public Criteria andHitcntLessThan(Integer value) {
            addCriterion("HITCNT <", value, "hitcnt");
            return (Criteria) this;
        }

        public Criteria andHitcntLessThanOrEqualTo(Integer value) {
            addCriterion("HITCNT <=", value, "hitcnt");
            return (Criteria) this;
        }

        public Criteria andHitcntIn(List<Integer> values) {
            addCriterion("HITCNT in", values, "hitcnt");
            return (Criteria) this;
        }

        public Criteria andHitcntNotIn(List<Integer> values) {
            addCriterion("HITCNT not in", values, "hitcnt");
            return (Criteria) this;
        }

        public Criteria andHitcntBetween(Integer value1, Integer value2) {
            addCriterion("HITCNT between", value1, value2, "hitcnt");
            return (Criteria) this;
        }

        public Criteria andHitcntNotBetween(Integer value1, Integer value2) {
            addCriterion("HITCNT not between", value1, value2, "hitcnt");
            return (Criteria) this;
        }

        public Criteria andReg_deIsNull() {
            addCriterion("REG_DE is null");
            return (Criteria) this;
        }

        public Criteria andReg_deIsNotNull() {
            addCriterion("REG_DE is not null");
            return (Criteria) this;
        }

        public Criteria andReg_deEqualTo(Date value) {
            addCriterion("REG_DE =", value, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deNotEqualTo(Date value) {
            addCriterion("REG_DE <>", value, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deGreaterThan(Date value) {
            addCriterion("REG_DE >", value, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deGreaterThanOrEqualTo(Date value) {
            addCriterion("REG_DE >=", value, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deLessThan(Date value) {
            addCriterion("REG_DE <", value, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deLessThanOrEqualTo(Date value) {
            addCriterion("REG_DE <=", value, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deIn(List<Date> values) {
            addCriterion("REG_DE in", values, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deNotIn(List<Date> values) {
            addCriterion("REG_DE not in", values, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deBetween(Date value1, Date value2) {
            addCriterion("REG_DE between", value1, value2, "reg_de");
            return (Criteria) this;
        }

        public Criteria andReg_deNotBetween(Date value1, Date value2) {
            addCriterion("REG_DE not between", value1, value2, "reg_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deIsNull() {
            addCriterion("UPD_DE is null");
            return (Criteria) this;
        }

        public Criteria andUpd_deIsNotNull() {
            addCriterion("UPD_DE is not null");
            return (Criteria) this;
        }

        public Criteria andUpd_deEqualTo(Date value) {
            addCriterion("UPD_DE =", value, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deNotEqualTo(Date value) {
            addCriterion("UPD_DE <>", value, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deGreaterThan(Date value) {
            addCriterion("UPD_DE >", value, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deGreaterThanOrEqualTo(Date value) {
            addCriterion("UPD_DE >=", value, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deLessThan(Date value) {
            addCriterion("UPD_DE <", value, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deLessThanOrEqualTo(Date value) {
            addCriterion("UPD_DE <=", value, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deIn(List<Date> values) {
            addCriterion("UPD_DE in", values, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deNotIn(List<Date> values) {
            addCriterion("UPD_DE not in", values, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deBetween(Date value1, Date value2) {
            addCriterion("UPD_DE between", value1, value2, "upd_de");
            return (Criteria) this;
        }

        public Criteria andUpd_deNotBetween(Date value1, Date value2) {
            addCriterion("UPD_DE not between", value1, value2, "upd_de");
            return (Criteria) this;
        }

        public Criteria andDel_ynIsNull() {
            addCriterion("DEL_YN is null");
            return (Criteria) this;
        }

        public Criteria andDel_ynIsNotNull() {
            addCriterion("DEL_YN is not null");
            return (Criteria) this;
        }

        public Criteria andDel_ynEqualTo(String value) {
            addCriterion("DEL_YN =", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynNotEqualTo(String value) {
            addCriterion("DEL_YN <>", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynGreaterThan(String value) {
            addCriterion("DEL_YN >", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynGreaterThanOrEqualTo(String value) {
            addCriterion("DEL_YN >=", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynLessThan(String value) {
            addCriterion("DEL_YN <", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynLessThanOrEqualTo(String value) {
            addCriterion("DEL_YN <=", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynLike(String value) {
            addCriterion("DEL_YN like", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynNotLike(String value) {
            addCriterion("DEL_YN not like", value, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynIn(List<String> values) {
            addCriterion("DEL_YN in", values, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynNotIn(List<String> values) {
            addCriterion("DEL_YN not in", values, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynBetween(String value1, String value2) {
            addCriterion("DEL_YN between", value1, value2, "del_yn");
            return (Criteria) this;
        }

        public Criteria andDel_ynNotBetween(String value1, String value2) {
            addCriterion("DEL_YN not between", value1, value2, "del_yn");
            return (Criteria) this;
        }

        public Criteria andCr_noIsNull() {
            addCriterion("CR_NO is null");
            return (Criteria) this;
        }

        public Criteria andCr_noIsNotNull() {
            addCriterion("CR_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCr_noEqualTo(String value) {
            addCriterion("CR_NO =", value, "cr_no");
            return (Criteria) this;
        }

        public Criteria andCr_noNotEqualTo(String value) {
            addCriterion("CR_NO <>", value, "cr_no");
            return (Criteria) this;
        }

        public Criteria andCr_noGreaterThan(String value) {
            addCriterion("CR_NO >", value, "cr_no");
            return (Criteria) this;
        }

        public Criteria andCr_noGreaterThanOrEqualTo(String value) {
            addCriterion("CR_NO >=", value, "cr_no");
            return (Criteria) this;
        }

        public Criteria andCr_noLessThan(String value) {
            addCriterion("CR_NO <", value, "cr_no");
            return (Criteria) this;
        }

        public Criteria andCr_noLessThanOrEqualTo(String value) {
            addCriterion("CR_NO <=", value, "cr_no");
            return (Criteria) this;
        }

        public Criteria andCr_noLike(String value) {
            addCriterion("CR_NO like", value, "cr_no");
            return (Criteria) this;
        }

        public Criteria andCr_noNotLike(String value) {
            addCriterion("CR_NO not like", value, "cr_no");
            return (Criteria) this;
        }

        public Criteria andCr_noIn(List<String> values) {
            addCriterion("CR_NO in", values, "cr_no");
            return (Criteria) this;
        }

        public Criteria andCr_noNotIn(List<String> values) {
            addCriterion("CR_NO not in", values, "cr_no");
            return (Criteria) this;
        }

        public Criteria andCr_noBetween(String value1, String value2) {
            addCriterion("CR_NO between", value1, value2, "cr_no");
            return (Criteria) this;
        }

        public Criteria andCr_noNotBetween(String value1, String value2) {
            addCriterion("CR_NO not between", value1, value2, "cr_no");
            return (Criteria) this;
        }

        public Criteria andWrterIsNull() {
            addCriterion("WRTER is null");
            return (Criteria) this;
        }

        public Criteria andWrterIsNotNull() {
            addCriterion("WRTER is not null");
            return (Criteria) this;
        }

        public Criteria andWrterEqualTo(String value) {
            addCriterion("WRTER =", value, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterNotEqualTo(String value) {
            addCriterion("WRTER <>", value, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterGreaterThan(String value) {
            addCriterion("WRTER >", value, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterGreaterThanOrEqualTo(String value) {
            addCriterion("WRTER >=", value, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterLessThan(String value) {
            addCriterion("WRTER <", value, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterLessThanOrEqualTo(String value) {
            addCriterion("WRTER <=", value, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterLike(String value) {
            addCriterion("WRTER like", value, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterNotLike(String value) {
            addCriterion("WRTER not like", value, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterIn(List<String> values) {
            addCriterion("WRTER in", values, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterNotIn(List<String> values) {
            addCriterion("WRTER not in", values, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterBetween(String value1, String value2) {
            addCriterion("WRTER between", value1, value2, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterNotBetween(String value1, String value2) {
            addCriterion("WRTER not between", value1, value2, "wrter");
            return (Criteria) this;
        }

        public Criteria andNotice_noIsNull() {
            addCriterion("NOTICE_NO is null");
            return (Criteria) this;
        }

        public Criteria andNotice_noIsNotNull() {
            addCriterion("NOTICE_NO is not null");
            return (Criteria) this;
        }

        public Criteria andNotice_noEqualTo(String value) {
            addCriterion("NOTICE_NO =", value, "notice_no");
            return (Criteria) this;
        }

        public Criteria andNotice_noNotEqualTo(String value) {
            addCriterion("NOTICE_NO <>", value, "notice_no");
            return (Criteria) this;
        }

        public Criteria andNotice_noGreaterThan(String value) {
            addCriterion("NOTICE_NO >", value, "notice_no");
            return (Criteria) this;
        }

        public Criteria andNotice_noGreaterThanOrEqualTo(String value) {
            addCriterion("NOTICE_NO >=", value, "notice_no");
            return (Criteria) this;
        }

        public Criteria andNotice_noLessThan(String value) {
            addCriterion("NOTICE_NO <", value, "notice_no");
            return (Criteria) this;
        }

        public Criteria andNotice_noLessThanOrEqualTo(String value) {
            addCriterion("NOTICE_NO <=", value, "notice_no");
            return (Criteria) this;
        }

        public Criteria andNotice_noLike(String value) {
            addCriterion("NOTICE_NO like", value, "notice_no");
            return (Criteria) this;
        }

        public Criteria andNotice_noNotLike(String value) {
            addCriterion("NOTICE_NO not like", value, "notice_no");
            return (Criteria) this;
        }

        public Criteria andNotice_noIn(List<String> values) {
            addCriterion("NOTICE_NO in", values, "notice_no");
            return (Criteria) this;
        }

        public Criteria andNotice_noNotIn(List<String> values) {
            addCriterion("NOTICE_NO not in", values, "notice_no");
            return (Criteria) this;
        }

        public Criteria andNotice_noBetween(String value1, String value2) {
            addCriterion("NOTICE_NO between", value1, value2, "notice_no");
            return (Criteria) this;
        }

        public Criteria andNotice_noNotBetween(String value1, String value2) {
            addCriterion("NOTICE_NO not between", value1, value2, "notice_no");
            return (Criteria) this;
        }

        public Criteria andUpdusrIsNull() {
            addCriterion("UPDUSR is null");
            return (Criteria) this;
        }

        public Criteria andUpdusrIsNotNull() {
            addCriterion("UPDUSR is not null");
            return (Criteria) this;
        }

        public Criteria andUpdusrEqualTo(String value) {
            addCriterion("UPDUSR =", value, "updusr");
            return (Criteria) this;
        }

        public Criteria andUpdusrNotEqualTo(String value) {
            addCriterion("UPDUSR <>", value, "updusr");
            return (Criteria) this;
        }

        public Criteria andUpdusrGreaterThan(String value) {
            addCriterion("UPDUSR >", value, "updusr");
            return (Criteria) this;
        }

        public Criteria andUpdusrGreaterThanOrEqualTo(String value) {
            addCriterion("UPDUSR >=", value, "updusr");
            return (Criteria) this;
        }

        public Criteria andUpdusrLessThan(String value) {
            addCriterion("UPDUSR <", value, "updusr");
            return (Criteria) this;
        }

        public Criteria andUpdusrLessThanOrEqualTo(String value) {
            addCriterion("UPDUSR <=", value, "updusr");
            return (Criteria) this;
        }

        public Criteria andUpdusrLike(String value) {
            addCriterion("UPDUSR like", value, "updusr");
            return (Criteria) this;
        }

        public Criteria andUpdusrNotLike(String value) {
            addCriterion("UPDUSR not like", value, "updusr");
            return (Criteria) this;
        }

        public Criteria andUpdusrIn(List<String> values) {
            addCriterion("UPDUSR in", values, "updusr");
            return (Criteria) this;
        }

        public Criteria andUpdusrNotIn(List<String> values) {
            addCriterion("UPDUSR not in", values, "updusr");
            return (Criteria) this;
        }

        public Criteria andUpdusrBetween(String value1, String value2) {
            addCriterion("UPDUSR between", value1, value2, "updusr");
            return (Criteria) this;
        }

        public Criteria andUpdusrNotBetween(String value1, String value2) {
            addCriterion("UPDUSR not between", value1, value2, "updusr");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CR_NOTICE_LIST
     *
     * @mbg.generated do_not_delete_during_merge Sat Feb 10 13:59:28 KST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CR_NOTICE_LIST
     *
     * @mbg.generated Sat Feb 10 13:59:28 KST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}