package tk.tourwith.project.crew.room.event.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tk.tourwith.project.crew.room.event.model.CrEventList;
import tk.tourwith.project.crew.room.event.model.CrEventListExample;

public interface CrEventListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_EVENT_LIST
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    long countByExample(CrEventListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_EVENT_LIST
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    int deleteByExample(CrEventListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_EVENT_LIST
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    int insert(CrEventList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_EVENT_LIST
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    int insertSelective(CrEventList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_EVENT_LIST
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    List<CrEventList> selectByExample(CrEventListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_EVENT_LIST
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    int updateByExampleSelective(@Param("record") CrEventList record, @Param("example") CrEventListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_EVENT_LIST
     *
     * @mbg.generated Sat Feb 10 14:15:37 KST 2018
     */
    int updateByExample(@Param("record") CrEventList record, @Param("example") CrEventListExample example);
}