package tk.tourwith.project.reply.crew.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tk.tourwith.project.reply.crew.model.CrRplyList;
import tk.tourwith.project.reply.crew.model.CrRplyListExample;

public interface CrRplyListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    long countByExample(CrRplyListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    int deleteByExample(CrRplyListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    int insert(CrRplyList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    int insertSelective(CrRplyList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    List<CrRplyList> selectByExampleWithBLOBs(CrRplyListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    List<CrRplyList> selectByExample(CrRplyListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    int updateByExampleSelective(@Param("record") CrRplyList record, @Param("example") CrRplyListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") CrRplyList record, @Param("example") CrRplyListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_RPLY_LIST
     *
     * @mbg.generated Sat Feb 10 14:03:15 KST 2018
     */
    int updateByExample(@Param("record") CrRplyList record, @Param("example") CrRplyListExample example);
}