package tk.tourwith.project.crew.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import tk.tourwith.project.crew.model.CrList;
import tk.tourwith.project.crew.model.CrListExample;

public interface CrListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_LIST
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    long countByExample(CrListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_LIST
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    int deleteByExample(CrListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_LIST
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    int insert(CrList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_LIST
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    int insertSelective(CrList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_LIST
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    List<CrList> selectByExampleWithBLOBs(CrListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_LIST
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    List<CrList> selectByExample(CrListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_LIST
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    int updateByExampleSelective(@Param("record") CrList record, @Param("example") CrListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_LIST
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") CrList record, @Param("example") CrListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CR_LIST
     *
     * @mbg.generated Sat Feb 10 13:37:29 KST 2018
     */
    int updateByExample(@Param("record") CrList record, @Param("example") CrListExample example);
}