package tk.tourwith.project.crew.room.gis.model;

import java.util.Date;

public class CrGisCrdntList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_GIS_CRDNT_LIST.GIS_CRDNT_NO
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    private String gis_crdnt_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_GIS_CRDNT_LIST.CRDNT_INDX
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    private String crdnt_indx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_GIS_CRDNT_LIST.REG_DE
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    private Date reg_de;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_GIS_CRDNT_LIST.REGISTER
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    private String register;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_GIS_CRDNT_LIST.UPDUSR
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    private String updusr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_GIS_CRDNT_LIST.UPD_DE
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    private Date upd_de;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_GIS_CRDNT_LIST.LATI
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    private Float lati;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_GIS_CRDNT_LIST.LONGI
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    private Float longi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CR_GIS_CRDNT_LIST.CR_NO
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    private String cr_no;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_GIS_CRDNT_LIST.GIS_CRDNT_NO
     *
     * @return the value of CR_GIS_CRDNT_LIST.GIS_CRDNT_NO
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    public String getGis_crdnt_no() {
        return gis_crdnt_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_GIS_CRDNT_LIST.GIS_CRDNT_NO
     *
     * @param gis_crdnt_no the value for CR_GIS_CRDNT_LIST.GIS_CRDNT_NO
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    public void setGis_crdnt_no(String gis_crdnt_no) {
        this.gis_crdnt_no = gis_crdnt_no == null ? null : gis_crdnt_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_GIS_CRDNT_LIST.CRDNT_INDX
     *
     * @return the value of CR_GIS_CRDNT_LIST.CRDNT_INDX
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    public String getCrdnt_indx() {
        return crdnt_indx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_GIS_CRDNT_LIST.CRDNT_INDX
     *
     * @param crdnt_indx the value for CR_GIS_CRDNT_LIST.CRDNT_INDX
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    public void setCrdnt_indx(String crdnt_indx) {
        this.crdnt_indx = crdnt_indx == null ? null : crdnt_indx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_GIS_CRDNT_LIST.REG_DE
     *
     * @return the value of CR_GIS_CRDNT_LIST.REG_DE
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    public Date getReg_de() {
        return reg_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_GIS_CRDNT_LIST.REG_DE
     *
     * @param reg_de the value for CR_GIS_CRDNT_LIST.REG_DE
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    public void setReg_de(Date reg_de) {
        this.reg_de = reg_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_GIS_CRDNT_LIST.REGISTER
     *
     * @return the value of CR_GIS_CRDNT_LIST.REGISTER
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    public String getRegister() {
        return register;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_GIS_CRDNT_LIST.REGISTER
     *
     * @param register the value for CR_GIS_CRDNT_LIST.REGISTER
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    public void setRegister(String register) {
        this.register = register == null ? null : register.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_GIS_CRDNT_LIST.UPDUSR
     *
     * @return the value of CR_GIS_CRDNT_LIST.UPDUSR
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    public String getUpdusr() {
        return updusr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_GIS_CRDNT_LIST.UPDUSR
     *
     * @param updusr the value for CR_GIS_CRDNT_LIST.UPDUSR
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    public void setUpdusr(String updusr) {
        this.updusr = updusr == null ? null : updusr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_GIS_CRDNT_LIST.UPD_DE
     *
     * @return the value of CR_GIS_CRDNT_LIST.UPD_DE
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    public Date getUpd_de() {
        return upd_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_GIS_CRDNT_LIST.UPD_DE
     *
     * @param upd_de the value for CR_GIS_CRDNT_LIST.UPD_DE
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    public void setUpd_de(Date upd_de) {
        this.upd_de = upd_de;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_GIS_CRDNT_LIST.LATI
     *
     * @return the value of CR_GIS_CRDNT_LIST.LATI
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    public Float getLati() {
        return lati;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_GIS_CRDNT_LIST.LATI
     *
     * @param lati the value for CR_GIS_CRDNT_LIST.LATI
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    public void setLati(Float lati) {
        this.lati = lati;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_GIS_CRDNT_LIST.LONGI
     *
     * @return the value of CR_GIS_CRDNT_LIST.LONGI
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    public Float getLongi() {
        return longi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_GIS_CRDNT_LIST.LONGI
     *
     * @param longi the value for CR_GIS_CRDNT_LIST.LONGI
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    public void setLongi(Float longi) {
        this.longi = longi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CR_GIS_CRDNT_LIST.CR_NO
     *
     * @return the value of CR_GIS_CRDNT_LIST.CR_NO
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    public String getCr_no() {
        return cr_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CR_GIS_CRDNT_LIST.CR_NO
     *
     * @param cr_no the value for CR_GIS_CRDNT_LIST.CR_NO
     *
     * @mbg.generated Sat Feb 10 14:23:15 KST 2018
     */
    public void setCr_no(String cr_no) {
        this.cr_no = cr_no == null ? null : cr_no.trim();
    }
}