package tk.tourwith.project.util.code.model;

import java.util.Date;

public class CodeList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CODE_LIST.CODE_NO
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    private String code_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CODE_LIST.CODE_RGSDE
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    private Date code_rgsde;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CODE_LIST.CODE_SE
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    private String code_se;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CODE_LIST.CODE_NM
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    private String code_nm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CODE_LIST.GROUP_CODE
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    private String group_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CODE_LIST.WRTER
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    private String wrter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CODE_LIST.CODE_NO
     *
     * @return the value of CODE_LIST.CODE_NO
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    public String getCode_no() {
        return code_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CODE_LIST.CODE_NO
     *
     * @param code_no the value for CODE_LIST.CODE_NO
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    public void setCode_no(String code_no) {
        this.code_no = code_no == null ? null : code_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CODE_LIST.CODE_RGSDE
     *
     * @return the value of CODE_LIST.CODE_RGSDE
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    public Date getCode_rgsde() {
        return code_rgsde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CODE_LIST.CODE_RGSDE
     *
     * @param code_rgsde the value for CODE_LIST.CODE_RGSDE
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    public void setCode_rgsde(Date code_rgsde) {
        this.code_rgsde = code_rgsde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CODE_LIST.CODE_SE
     *
     * @return the value of CODE_LIST.CODE_SE
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    public String getCode_se() {
        return code_se;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CODE_LIST.CODE_SE
     *
     * @param code_se the value for CODE_LIST.CODE_SE
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    public void setCode_se(String code_se) {
        this.code_se = code_se == null ? null : code_se.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CODE_LIST.CODE_NM
     *
     * @return the value of CODE_LIST.CODE_NM
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    public String getCode_nm() {
        return code_nm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CODE_LIST.CODE_NM
     *
     * @param code_nm the value for CODE_LIST.CODE_NM
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    public void setCode_nm(String code_nm) {
        this.code_nm = code_nm == null ? null : code_nm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CODE_LIST.GROUP_CODE
     *
     * @return the value of CODE_LIST.GROUP_CODE
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    public String getGroup_code() {
        return group_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CODE_LIST.GROUP_CODE
     *
     * @param group_code the value for CODE_LIST.GROUP_CODE
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    public void setGroup_code(String group_code) {
        this.group_code = group_code == null ? null : group_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CODE_LIST.WRTER
     *
     * @return the value of CODE_LIST.WRTER
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    public String getWrter() {
        return wrter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CODE_LIST.WRTER
     *
     * @param wrter the value for CODE_LIST.WRTER
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    public void setWrter(String wrter) {
        this.wrter = wrter == null ? null : wrter.trim();
    }
}