package tk.tourwith.project.util.code.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CodeListExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CODE_LIST
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CODE_LIST
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CODE_LIST
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_LIST
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    public CodeListExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_LIST
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_LIST
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_LIST
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_LIST
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_LIST
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_LIST
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_LIST
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_LIST
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_LIST
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CODE_LIST
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CODE_LIST
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCode_noIsNull() {
            addCriterion("CODE_NO is null");
            return (Criteria) this;
        }

        public Criteria andCode_noIsNotNull() {
            addCriterion("CODE_NO is not null");
            return (Criteria) this;
        }

        public Criteria andCode_noEqualTo(String value) {
            addCriterion("CODE_NO =", value, "code_no");
            return (Criteria) this;
        }

        public Criteria andCode_noNotEqualTo(String value) {
            addCriterion("CODE_NO <>", value, "code_no");
            return (Criteria) this;
        }

        public Criteria andCode_noGreaterThan(String value) {
            addCriterion("CODE_NO >", value, "code_no");
            return (Criteria) this;
        }

        public Criteria andCode_noGreaterThanOrEqualTo(String value) {
            addCriterion("CODE_NO >=", value, "code_no");
            return (Criteria) this;
        }

        public Criteria andCode_noLessThan(String value) {
            addCriterion("CODE_NO <", value, "code_no");
            return (Criteria) this;
        }

        public Criteria andCode_noLessThanOrEqualTo(String value) {
            addCriterion("CODE_NO <=", value, "code_no");
            return (Criteria) this;
        }

        public Criteria andCode_noLike(String value) {
            addCriterion("CODE_NO like", value, "code_no");
            return (Criteria) this;
        }

        public Criteria andCode_noNotLike(String value) {
            addCriterion("CODE_NO not like", value, "code_no");
            return (Criteria) this;
        }

        public Criteria andCode_noIn(List<String> values) {
            addCriterion("CODE_NO in", values, "code_no");
            return (Criteria) this;
        }

        public Criteria andCode_noNotIn(List<String> values) {
            addCriterion("CODE_NO not in", values, "code_no");
            return (Criteria) this;
        }

        public Criteria andCode_noBetween(String value1, String value2) {
            addCriterion("CODE_NO between", value1, value2, "code_no");
            return (Criteria) this;
        }

        public Criteria andCode_noNotBetween(String value1, String value2) {
            addCriterion("CODE_NO not between", value1, value2, "code_no");
            return (Criteria) this;
        }

        public Criteria andCode_rgsdeIsNull() {
            addCriterion("CODE_RGSDE is null");
            return (Criteria) this;
        }

        public Criteria andCode_rgsdeIsNotNull() {
            addCriterion("CODE_RGSDE is not null");
            return (Criteria) this;
        }

        public Criteria andCode_rgsdeEqualTo(Date value) {
            addCriterion("CODE_RGSDE =", value, "code_rgsde");
            return (Criteria) this;
        }

        public Criteria andCode_rgsdeNotEqualTo(Date value) {
            addCriterion("CODE_RGSDE <>", value, "code_rgsde");
            return (Criteria) this;
        }

        public Criteria andCode_rgsdeGreaterThan(Date value) {
            addCriterion("CODE_RGSDE >", value, "code_rgsde");
            return (Criteria) this;
        }

        public Criteria andCode_rgsdeGreaterThanOrEqualTo(Date value) {
            addCriterion("CODE_RGSDE >=", value, "code_rgsde");
            return (Criteria) this;
        }

        public Criteria andCode_rgsdeLessThan(Date value) {
            addCriterion("CODE_RGSDE <", value, "code_rgsde");
            return (Criteria) this;
        }

        public Criteria andCode_rgsdeLessThanOrEqualTo(Date value) {
            addCriterion("CODE_RGSDE <=", value, "code_rgsde");
            return (Criteria) this;
        }

        public Criteria andCode_rgsdeIn(List<Date> values) {
            addCriterion("CODE_RGSDE in", values, "code_rgsde");
            return (Criteria) this;
        }

        public Criteria andCode_rgsdeNotIn(List<Date> values) {
            addCriterion("CODE_RGSDE not in", values, "code_rgsde");
            return (Criteria) this;
        }

        public Criteria andCode_rgsdeBetween(Date value1, Date value2) {
            addCriterion("CODE_RGSDE between", value1, value2, "code_rgsde");
            return (Criteria) this;
        }

        public Criteria andCode_rgsdeNotBetween(Date value1, Date value2) {
            addCriterion("CODE_RGSDE not between", value1, value2, "code_rgsde");
            return (Criteria) this;
        }

        public Criteria andCode_seIsNull() {
            addCriterion("CODE_SE is null");
            return (Criteria) this;
        }

        public Criteria andCode_seIsNotNull() {
            addCriterion("CODE_SE is not null");
            return (Criteria) this;
        }

        public Criteria andCode_seEqualTo(String value) {
            addCriterion("CODE_SE =", value, "code_se");
            return (Criteria) this;
        }

        public Criteria andCode_seNotEqualTo(String value) {
            addCriterion("CODE_SE <>", value, "code_se");
            return (Criteria) this;
        }

        public Criteria andCode_seGreaterThan(String value) {
            addCriterion("CODE_SE >", value, "code_se");
            return (Criteria) this;
        }

        public Criteria andCode_seGreaterThanOrEqualTo(String value) {
            addCriterion("CODE_SE >=", value, "code_se");
            return (Criteria) this;
        }

        public Criteria andCode_seLessThan(String value) {
            addCriterion("CODE_SE <", value, "code_se");
            return (Criteria) this;
        }

        public Criteria andCode_seLessThanOrEqualTo(String value) {
            addCriterion("CODE_SE <=", value, "code_se");
            return (Criteria) this;
        }

        public Criteria andCode_seLike(String value) {
            addCriterion("CODE_SE like", value, "code_se");
            return (Criteria) this;
        }

        public Criteria andCode_seNotLike(String value) {
            addCriterion("CODE_SE not like", value, "code_se");
            return (Criteria) this;
        }

        public Criteria andCode_seIn(List<String> values) {
            addCriterion("CODE_SE in", values, "code_se");
            return (Criteria) this;
        }

        public Criteria andCode_seNotIn(List<String> values) {
            addCriterion("CODE_SE not in", values, "code_se");
            return (Criteria) this;
        }

        public Criteria andCode_seBetween(String value1, String value2) {
            addCriterion("CODE_SE between", value1, value2, "code_se");
            return (Criteria) this;
        }

        public Criteria andCode_seNotBetween(String value1, String value2) {
            addCriterion("CODE_SE not between", value1, value2, "code_se");
            return (Criteria) this;
        }

        public Criteria andCode_nmIsNull() {
            addCriterion("CODE_NM is null");
            return (Criteria) this;
        }

        public Criteria andCode_nmIsNotNull() {
            addCriterion("CODE_NM is not null");
            return (Criteria) this;
        }

        public Criteria andCode_nmEqualTo(String value) {
            addCriterion("CODE_NM =", value, "code_nm");
            return (Criteria) this;
        }

        public Criteria andCode_nmNotEqualTo(String value) {
            addCriterion("CODE_NM <>", value, "code_nm");
            return (Criteria) this;
        }

        public Criteria andCode_nmGreaterThan(String value) {
            addCriterion("CODE_NM >", value, "code_nm");
            return (Criteria) this;
        }

        public Criteria andCode_nmGreaterThanOrEqualTo(String value) {
            addCriterion("CODE_NM >=", value, "code_nm");
            return (Criteria) this;
        }

        public Criteria andCode_nmLessThan(String value) {
            addCriterion("CODE_NM <", value, "code_nm");
            return (Criteria) this;
        }

        public Criteria andCode_nmLessThanOrEqualTo(String value) {
            addCriterion("CODE_NM <=", value, "code_nm");
            return (Criteria) this;
        }

        public Criteria andCode_nmLike(String value) {
            addCriterion("CODE_NM like", value, "code_nm");
            return (Criteria) this;
        }

        public Criteria andCode_nmNotLike(String value) {
            addCriterion("CODE_NM not like", value, "code_nm");
            return (Criteria) this;
        }

        public Criteria andCode_nmIn(List<String> values) {
            addCriterion("CODE_NM in", values, "code_nm");
            return (Criteria) this;
        }

        public Criteria andCode_nmNotIn(List<String> values) {
            addCriterion("CODE_NM not in", values, "code_nm");
            return (Criteria) this;
        }

        public Criteria andCode_nmBetween(String value1, String value2) {
            addCriterion("CODE_NM between", value1, value2, "code_nm");
            return (Criteria) this;
        }

        public Criteria andCode_nmNotBetween(String value1, String value2) {
            addCriterion("CODE_NM not between", value1, value2, "code_nm");
            return (Criteria) this;
        }

        public Criteria andGroup_codeIsNull() {
            addCriterion("GROUP_CODE is null");
            return (Criteria) this;
        }

        public Criteria andGroup_codeIsNotNull() {
            addCriterion("GROUP_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andGroup_codeEqualTo(String value) {
            addCriterion("GROUP_CODE =", value, "group_code");
            return (Criteria) this;
        }

        public Criteria andGroup_codeNotEqualTo(String value) {
            addCriterion("GROUP_CODE <>", value, "group_code");
            return (Criteria) this;
        }

        public Criteria andGroup_codeGreaterThan(String value) {
            addCriterion("GROUP_CODE >", value, "group_code");
            return (Criteria) this;
        }

        public Criteria andGroup_codeGreaterThanOrEqualTo(String value) {
            addCriterion("GROUP_CODE >=", value, "group_code");
            return (Criteria) this;
        }

        public Criteria andGroup_codeLessThan(String value) {
            addCriterion("GROUP_CODE <", value, "group_code");
            return (Criteria) this;
        }

        public Criteria andGroup_codeLessThanOrEqualTo(String value) {
            addCriterion("GROUP_CODE <=", value, "group_code");
            return (Criteria) this;
        }

        public Criteria andGroup_codeLike(String value) {
            addCriterion("GROUP_CODE like", value, "group_code");
            return (Criteria) this;
        }

        public Criteria andGroup_codeNotLike(String value) {
            addCriterion("GROUP_CODE not like", value, "group_code");
            return (Criteria) this;
        }

        public Criteria andGroup_codeIn(List<String> values) {
            addCriterion("GROUP_CODE in", values, "group_code");
            return (Criteria) this;
        }

        public Criteria andGroup_codeNotIn(List<String> values) {
            addCriterion("GROUP_CODE not in", values, "group_code");
            return (Criteria) this;
        }

        public Criteria andGroup_codeBetween(String value1, String value2) {
            addCriterion("GROUP_CODE between", value1, value2, "group_code");
            return (Criteria) this;
        }

        public Criteria andGroup_codeNotBetween(String value1, String value2) {
            addCriterion("GROUP_CODE not between", value1, value2, "group_code");
            return (Criteria) this;
        }

        public Criteria andWrterIsNull() {
            addCriterion("WRTER is null");
            return (Criteria) this;
        }

        public Criteria andWrterIsNotNull() {
            addCriterion("WRTER is not null");
            return (Criteria) this;
        }

        public Criteria andWrterEqualTo(String value) {
            addCriterion("WRTER =", value, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterNotEqualTo(String value) {
            addCriterion("WRTER <>", value, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterGreaterThan(String value) {
            addCriterion("WRTER >", value, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterGreaterThanOrEqualTo(String value) {
            addCriterion("WRTER >=", value, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterLessThan(String value) {
            addCriterion("WRTER <", value, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterLessThanOrEqualTo(String value) {
            addCriterion("WRTER <=", value, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterLike(String value) {
            addCriterion("WRTER like", value, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterNotLike(String value) {
            addCriterion("WRTER not like", value, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterIn(List<String> values) {
            addCriterion("WRTER in", values, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterNotIn(List<String> values) {
            addCriterion("WRTER not in", values, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterBetween(String value1, String value2) {
            addCriterion("WRTER between", value1, value2, "wrter");
            return (Criteria) this;
        }

        public Criteria andWrterNotBetween(String value1, String value2) {
            addCriterion("WRTER not between", value1, value2, "wrter");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CODE_LIST
     *
     * @mbg.generated do_not_delete_during_merge Fri Feb 09 14:27:56 KST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CODE_LIST
     *
     * @mbg.generated Fri Feb 09 14:27:56 KST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}