package tk.tourwith.project.util.trplc.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tk.tourwith.project.util.trplc.model.TrplcInfoManage;
import tk.tourwith.project.util.trplc.model.TrplcInfoManageExample;

public interface TrplcInfoManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRPLC_INFO_MANAGE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    long countByExample(TrplcInfoManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRPLC_INFO_MANAGE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    int deleteByExample(TrplcInfoManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRPLC_INFO_MANAGE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    int deleteByPrimaryKey(String trplc_no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRPLC_INFO_MANAGE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    int insert(TrplcInfoManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRPLC_INFO_MANAGE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    int insertSelective(TrplcInfoManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRPLC_INFO_MANAGE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    List<TrplcInfoManage> selectByExample(TrplcInfoManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRPLC_INFO_MANAGE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    TrplcInfoManage selectByPrimaryKey(String trplc_no);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRPLC_INFO_MANAGE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    int updateByExampleSelective(@Param("record") TrplcInfoManage record, @Param("example") TrplcInfoManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRPLC_INFO_MANAGE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    int updateByExample(@Param("record") TrplcInfoManage record, @Param("example") TrplcInfoManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRPLC_INFO_MANAGE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    int updateByPrimaryKeySelective(TrplcInfoManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TRPLC_INFO_MANAGE
     *
     * @mbg.generated Fri Feb 09 12:28:44 KST 2018
     */
    int updateByPrimaryKey(TrplcInfoManage record);
}